// Civics & Government data — aligned to the Massachusetts 2018 HSS Framework,
// Grade 8 "U.S. and Massachusetts Government and Civic Life."
// Content is kept accurate and 8th-grade friendly. Every game's reveal points
// back to a real, citable source listed in SOURCES.
// `eli5` fields are super-simple analogies shown in a "Like you're 5" box.
window.CIVICS = {

  // ---- Sources (shown in the 📚 Sources popup and cited in reveals) ----
  SOURCES: [
    { key: 'ma',        name: 'MA 2018 History & Social Science Framework (Grade 8 Civics)', url: 'https://www.doe.mass.edu/frameworks/hss/2018-12.pdf', note: 'The Massachusetts standards this game is built on.' },
    { key: 'archives',  name: 'U.S. Constitution — National Archives', url: 'https://www.archives.gov/founding-docs/constitution', note: 'Full text of the Constitution and its amendments.' },
    { key: 'bor',       name: 'The Bill of Rights — National Archives', url: 'https://www.archives.gov/founding-docs/bill-of-rights', note: 'The first 10 amendments, in the founders’ own words.' },
    { key: 'doi',       name: 'Declaration of Independence — National Archives', url: 'https://www.archives.gov/founding-docs/declaration', note: 'The 1776 document that declared independence.' },
    { key: 'congress',  name: 'How Our Laws Are Made — Congress.gov', url: 'https://www.congress.gov/help/learn-about-the-legislative-process/how-our-laws-are-made', note: 'The official step-by-step of how a bill becomes a law.' },
    { key: 'usagov',    name: 'How the U.S. Government Is Organized — USA.gov', url: 'https://www.usa.gov/branches-of-government', note: 'Plain-language overview of the three branches.' },
    { key: 'icivics',   name: 'iCivics', url: 'https://www.icivics.org/', note: 'Free civics lessons and games (founded by Justice Sandra Day O’Connor).' },
    { key: 'court',     name: 'About the Supreme Court — U.S. Courts', url: 'https://www.uscourts.gov/about-federal-courts/educational-resources/about-educational-outreach/activity-resources/about', note: 'What the federal courts and Supreme Court do.' },
    { key: 'mass',      name: 'Massachusetts Constitution & Town Meeting — Mass.gov', url: 'https://www.mass.gov/the-massachusetts-state-constitution', note: 'The 1780 state constitution and local town-meeting government.' },
    { key: 'factbook',  name: 'The World Factbook — Government Types', url: 'https://www.cia.gov/the-world-factbook/field/government-type/', note: 'How the government of every country is classified.' },
    { key: 'freedom',   name: 'Freedom House — Freedom in the World', url: 'https://freedomhouse.org/countries/freedom-world/scores', note: 'Yearly ratings of political rights and civil liberties by country.' }
  ],

  // =====================================================================
  // GAME 1 — TERMS: match the civics term to what it means.
  // `def` = the clue shown, `kid` = friendly restatement, `ex` = an example.
  // =====================================================================
  TERMS: [
    { term: 'Legislative Branch', icon: '🏛️', cat: 'branches', img: 'img/capitol.webp',
      def: 'The branch of government that makes the laws.',
      kid: 'Congress — the Senate and the House of Representatives — writes and passes the laws.',
      ex: 'Passing a national budget or a new law about clean water.',
      eli5: 'They’re the rule-writers — the group that makes up the rules of the game.' },
    { term: 'Executive Branch', icon: '🦅', cat: 'branches', img: 'img/whitehouse.webp',
      def: 'The branch of government that carries out and enforces the laws.',
      kid: 'The President leads it, along with the Cabinet and agencies, and makes sure laws are followed.',
      ex: 'The President signs a bill into law or commands the military.',
      eli5: 'The head referee — makes sure everyone actually follows the rules.' },
    { term: 'Judicial Branch', icon: '⚖️', cat: 'branches', img: 'img/supremecourt.webp',
      def: 'The branch of government that interprets the laws and settles disputes.',
      kid: 'The courts — topped by the Supreme Court — decide what laws mean and whether they follow the Constitution.',
      ex: 'The Supreme Court deciding if a law is constitutional.',
      eli5: 'The umpires — when people disagree about a rule, they decide what it really means.' },
    { term: 'Checks and Balances', icon: '⚖️', cat: 'system',
      def: 'The system that lets each branch limit the power of the other two.',
      kid: 'No branch can get too powerful — each one can check the others.',
      ex: 'The President can veto a bill; Congress can override the veto; courts can strike laws down.',
      eli5: 'Like rock-paper-scissors: every branch can beat another, so nobody wins forever.' },
    { term: 'Separation of Powers', icon: '🧩', cat: 'system',
      def: 'Dividing government power among three separate branches.',
      kid: 'Splitting the job of governing so no single group controls everything.',
      ex: 'Law-making, law-enforcing, and law-judging are done by different branches.',
      eli5: 'Don’t let one kid write the rules, enforce the rules, AND judge the rules — split up the jobs.' },
    { term: 'Federalism', icon: '🗺️', cat: 'system',
      def: 'Sharing power between a national government and state governments.',
      kid: 'Some powers belong to the whole country, some to each state, and some are shared.',
      ex: 'The nation runs the military; states run public schools.',
      eli5: 'The school makes school-wide rules, but each classroom still makes its own rules too.' },
    { term: 'Constitution', icon: '📜', cat: 'documents', img: 'img/constitution.webp',
      def: 'The supreme law that sets up the government and its powers.',
      kid: 'The rulebook for the whole U.S. government — the highest law in the land.',
      ex: 'It creates Congress, the presidency, and the courts.',
      eli5: 'The rulebook everyone has to play by — even the President.' },
    { term: 'Bill of Rights', icon: '📃', cat: 'documents', img: 'img/billofrights.webp',
      def: 'The first ten amendments to the Constitution, protecting individual freedoms.',
      kid: 'Ten promises added in 1791 that protect your basic rights from the government.',
      ex: 'Free speech, freedom of religion, and the right to a fair trial.',
      eli5: 'The “you can’t touch this” list — ten things the government can never take from you.' },
    { term: 'Declaration of Independence', icon: '🖋️', cat: 'documents', img: 'img/declaration.webp',
      def: 'The 1776 document that announced the colonies were free from Britain.',
      kid: 'It declared independence and said all people have rights like life, liberty, and the pursuit of happiness.',
      ex: 'Adopted July 4, 1776 — it explained WHY the colonies broke away.',
      eli5: 'America’s breakup letter to Britain: “We’re done — and here’s why.”' },
    { term: 'Amendment', icon: '✏️', cat: 'documents',
      def: 'An official change or addition to the Constitution.',
      kid: 'A way to update the Constitution — there have been 27 so far.',
      ex: 'The 19th Amendment gave women the right to vote.',
      eli5: 'A pencil-and-eraser for the Constitution — the official way to update the rulebook.' },
    { term: 'Democracy', icon: '🗳️', cat: 'systems',
      def: 'A form of government in which the people hold the power.',
      kid: 'Rule by the people — citizens make decisions, often by voting.',
      ex: 'Citizens vote to choose their leaders and shape the laws.',
      eli5: 'Everyone gets a say — the people are the boss.' },
    { term: 'Republic', icon: '🏛️', cat: 'systems',
      def: 'A government where people elect representatives to make decisions for them.',
      kid: 'You don’t vote on every law — you vote for leaders who do it for you.',
      ex: 'Americans elect members of Congress to write laws.',
      eli5: 'You pick a classmate to speak for the whole class instead of everyone shouting at once.' },
    { term: 'Monarchy', icon: '👑', cat: 'systems',
      def: 'A government led by a king or queen, often inheriting the throne.',
      kid: 'One royal ruler is in charge, usually passed down through a family.',
      ex: 'Saudi Arabia is ruled by a king with real power.',
      eli5: 'One family wears the crown, and “ruler” gets passed down like a family heirloom.' },
    { term: 'Popular Sovereignty', icon: '🙋', cat: 'system',
      def: 'The idea that government gets its power from the consent of the people.',
      kid: 'The government only has power because the people give it power.',
      ex: 'The Constitution begins “We the People…”.',
      eli5: 'The government works for you — the people are the boss, not the other way around.' },
    { term: 'Veto', icon: '🚫', cat: 'system',
      def: 'The President’s power to reject a bill passed by Congress.',
      kid: 'The President can say “no” to a bill and send it back.',
      ex: 'Congress can override a veto with a two-thirds vote.',
      eli5: 'The President’s big red NO stamp.' },
    { term: 'Bill', icon: '📄', cat: 'lawmaking',
      def: 'A proposed law being considered by a legislature.',
      kid: 'An idea for a law before it has been passed and signed.',
      ex: 'A bill must pass both houses of Congress to move forward.',
      eli5: 'A law that’s still just an idea — a rough draft before it gets graded.' },
    { term: 'Political Party', icon: '🎗️', cat: 'participation',
      def: 'An organized group that shares ideas and runs candidates for office.',
      kid: 'A team of people with similar beliefs who try to win elections.',
      ex: 'The Democratic and Republican parties in the U.S.',
      eli5: 'A team of people who agree on stuff and try to win elections together.' },
    { term: 'Jury', icon: '👥', cat: 'participation', img: 'img/jury.webp',
      def: 'A group of citizens who decide the facts of a court case.',
      kid: 'Ordinary people who listen to a trial and reach a verdict.',
      ex: 'A jury of 12 decides whether someone is guilty.',
      eli5: 'Regular people — not just judges — get to decide the case, so it stays fair.' },
    { term: 'Suffrage', icon: '🗳️', cat: 'participation', img: 'img/voting.webp',
      def: 'The right to vote in elections.',
      kid: 'Being allowed to vote — a right expanded many times in U.S. history.',
      ex: 'The 15th, 19th, and 26th Amendments all expanded suffrage.',
      eli5: 'Being allowed to vote. (Nothing to do with suffering — it comes from an old word for “vote.”)' },
    { term: 'Town Meeting', icon: '🏘️', cat: 'ma', img: 'img/townmeeting.webp',
      def: 'A form of local government where residents gather to vote directly on town matters.',
      kid: 'In many Massachusetts towns, citizens meet and vote in person on the budget and local rules.',
      ex: 'Plymouth, MA and many New England towns still use town meeting.',
      eli5: 'The whole town shows up and votes by raising hands — democracy in one room.' },
    { term: 'Ratify', icon: '✅', cat: 'documents',
      def: 'To formally approve something, like the Constitution or an amendment.',
      kid: 'To officially say “yes” and make it count.',
      ex: 'The states ratified the Constitution in 1788.',
      eli5: 'The official “yes, let’s make it real” vote.' },
    { term: 'Rule of Law', icon: '📏', cat: 'system',
      def: 'The idea that everyone, including leaders, must obey the law.',
      kid: 'No one is above the law — not even the President.',
      ex: 'A leader can be taken to court just like anyone else.',
      eli5: 'The rules apply to EVERYONE — even the person who made them.' }
  ],
  TERM_CATS: [
    ['all', 'All'], ['branches', '🏛️ Branches'], ['system', '⚙️ How It Works'],
    ['documents', '📜 Documents'], ['systems', '🗳️ Gov. Types'],
    ['participation', '🙋 Taking Part'], ['lawmaking', '📄 Lawmaking'], ['ma', '🦞 Massachusetts']
  ],

  // =====================================================================
  // GAME 2 — CONSTITUTION QUIZ: multiple-choice, straight from the
  // framework's 20 questions (plus a few extras). Each has a source key.
  // `dia` links the reveal to a diagram in the 📖 Diagrams popup.
  // =====================================================================
  CONSTITUTION: [
    { q: 'What are the three branches of the U.S. government?',
      choices: ['Legislative, Executive, Judicial', 'Federal, State, Local', 'House, Senate, President', 'Army, Navy, Air Force'],
      answer: 0, src: 'usagov', dia: 'checks',
      explain: 'The Legislative branch makes laws, the Executive branch carries them out, and the Judicial branch interprets them.',
      eli5: 'Making rules, enforcing rules, and judging rules — three jobs, three teams.' },
    { q: 'What is the main purpose of the U.S. Constitution?',
      choices: ['To set up the government and protect people’s rights', 'To declare war on Britain', 'To list the 50 states', 'To choose a national anthem'],
      answer: 0, src: 'archives',
      explain: 'The Constitution creates the framework of government and limits its power to protect the people’s rights. It is the supreme law of the land.',
      eli5: 'It’s the instruction manual AND the rulebook for America, all in one.' },
    { q: 'What does the system of "checks and balances" do?',
      choices: ['Lets each branch limit the power of the others', 'Balances the national budget', 'Counts the votes in an election', 'Divides the country into states'],
      answer: 0, src: 'usagov', dia: 'checks',
      explain: 'Each branch can “check” the others so no single branch becomes too powerful — for example, the President can veto a law and courts can strike it down.',
      eli5: 'Rock-paper-scissors: every branch can beat another, so nobody wins forever.' },
    { q: 'Which of these is a right protected by the First Amendment?',
      choices: ['Freedom of speech', 'The right to a driver’s license', 'The right to free healthcare', 'The right to own a car'],
      answer: 0, src: 'bor',
      explain: 'The First Amendment protects five freedoms: religion, speech, press, assembly, and petition.',
      eli5: 'You can say what you think — even about the government — without getting punished for it.' },
    { q: 'How is the Declaration of Independence different from the Constitution?',
      choices: ['It declared freedom from Britain; the Constitution sets up the government', 'They are the same document', 'The Declaration created Congress', 'The Constitution came first'],
      answer: 0, src: 'doi',
      explain: 'The Declaration (1776) announced independence and its reasons. The Constitution (1787) later built the actual government.',
      eli5: 'The Declaration is the breakup letter; the Constitution is the new house rules.' },
    { q: 'What is federalism?',
      choices: ['Sharing power between the national and state governments', 'Rule by a single king', 'A tax on imported goods', 'A type of election'],
      answer: 0, src: 'ma', dia: 'venn',
      explain: 'Under federalism, some powers belong to the national government, some to the states, and some are shared.',
      eli5: 'School-wide rules vs. classroom rules — some things the whole school decides, some things each class decides.' },
    { q: 'What is the Bill of Rights?',
      choices: ['The first ten amendments to the Constitution', 'The list of U.S. presidents', 'A tax law', 'The rules of Congress'],
      answer: 0, src: 'bor',
      explain: 'The Bill of Rights (ratified 1791) is the first ten amendments, protecting freedoms like speech, religion, and a fair trial.',
      eli5: 'The top-10 list of things the government can never take away from you.' },
    { q: 'Which is a RESPONSIBILITY of a citizen (not just a right)?',
      choices: ['Serving on a jury when called', 'Speaking freely', 'Practicing any religion', 'Owning property'],
      answer: 0, src: 'ma',
      explain: 'Rights are freedoms you’re guaranteed; responsibilities are duties you’re expected to fulfill, like serving on a jury, obeying laws, and voting.',
      eli5: 'A right is something you GET; a responsibility is something you’re expected to DO.' },
    { q: 'At the federal level, where does a bill usually START on its way to becoming a law?',
      choices: ['It is introduced in Congress (House or Senate)', 'The President writes it alone', 'The Supreme Court passes it', 'The states vote on it first'],
      answer: 0, src: 'congress', dia: 'bill',
      explain: 'A bill is introduced in Congress, studied in committee, passed by both the House and Senate, and then signed by the President to become law.',
      eli5: 'A law starts as homework in Congress — it gets checked lots of times before it counts.' },
    { q: 'What are the three LEVELS of government in the United States?',
      choices: ['Federal, State, Local', 'Legislative, Executive, Judicial', 'City, County, Town', 'Mayor, Governor, President'],
      answer: 0, src: 'usagov', dia: 'pyramid',
      explain: 'Government works at three levels: federal (national), state, and local (city or town).',
      eli5: 'Country-wide, state-wide, and your-own-town — like principal, teacher, and group leader.' },
    { q: 'What is the main role of the Supreme Court?',
      choices: ['To interpret the Constitution and decide if laws are constitutional', 'To write new laws', 'To command the army', 'To collect taxes'],
      answer: 0, src: 'court',
      explain: 'The Supreme Court is the highest court. It interprets the Constitution and can declare laws or actions unconstitutional.',
      eli5: 'The final umpire — their call on what the rules mean is the last word.' },
    { q: 'Besides voting, name one way a citizen can take part in democracy.',
      choices: ['Attending a town meeting or contacting an official', 'Ignoring the news', 'Paying no taxes', 'Refusing jury duty'],
      answer: 0, src: 'icivics',
      explain: 'Citizens can volunteer, join groups, contact officials, protest peacefully, serve on juries, or attend meetings — not just vote.',
      eli5: 'Democracy isn’t just voting day — you can speak up, help out, and show up all year long.' },
    { q: 'What is the main difference between a democracy and a monarchy?',
      choices: ['In a democracy the people hold power; in a monarchy a king or queen does', 'They are the same', 'A democracy has no laws', 'A monarchy has no leader'],
      answer: 0, src: 'ma',
      explain: 'In a democracy, power comes from the people. In a monarchy, a king or queen rules — sometimes with total power, sometimes only as a symbol.',
      eli5: 'Everyone’s the boss vs. one crowned boss.' },
    { q: 'The U.S. is a "representative democracy," or republic. What does that mean?',
      choices: ['People elect representatives to make laws for them', 'Everyone votes on every single law', 'A king makes the laws', 'Only judges make decisions'],
      answer: 0, src: 'ma',
      explain: 'Instead of voting on every law directly, citizens elect representatives (like members of Congress) to make decisions for them.',
      eli5: 'You pick someone to speak for you instead of everyone voting on every single thing.' },
    { q: 'Who heads the executive branch at the FEDERAL level?',
      choices: ['The President', 'The Speaker of the House', 'The Chief Justice', 'A governor'],
      answer: 0, src: 'usagov', dia: 'pyramid',
      explain: 'The President heads the federal executive branch. At the STATE level, a governor heads the executive branch.',
      eli5: 'The President runs the country’s to-do list; a governor runs the state’s.' },
    { q: 'What is the purpose of political parties?',
      choices: ['To organize people with similar ideas and run candidates', 'To count votes officially', 'To act as judges', 'To collect taxes'],
      answer: 0, src: 'icivics',
      explain: 'Political parties group people with shared ideas, choose candidates, and help voters understand what candidates stand for.',
      eli5: 'Teams for elections — people who agree on stuff working together to win.' },
    { q: 'What does "popular sovereignty" mean?',
      choices: ['Government’s power comes from the people', 'The most popular person becomes king', 'The majority is always right', 'Only landowners can vote'],
      answer: 0, src: 'ma',
      explain: 'Popular sovereignty means government gets its authority from the consent of the people — “We the People.”',
      eli5: 'The people are the boss. The government works for us, not the other way around.' },
    { q: 'Why does serving on a jury matter?',
      choices: ['Ordinary citizens help decide court cases fairly', 'Juries write new laws', 'Juries elect the President', 'Juries set tax rates'],
      answer: 0, src: 'court',
      explain: 'A jury of everyday citizens decides the facts of a case, which keeps the justice system fair and in the hands of the people.',
      eli5: 'Regular people make sure trials stay fair — not just the people in charge.' },
    { q: 'In Massachusetts, what is a "town meeting"?',
      choices: ['Residents gather and vote directly on local matters', 'A meeting of the governor and mayors', 'A statewide election', 'A session of Congress'],
      answer: 0, src: 'mass',
      explain: 'Many Massachusetts towns, like Plymouth, use town meeting — a form of direct democracy where residents vote in person on the budget and local rules.',
      eli5: 'The whole town raises hands to vote — democracy in one big room.' },
    { q: 'Why is the right to vote considered so important in a democracy?',
      choices: ['It lets people choose their leaders and shape the laws', 'It is required to get a job', 'It lowers taxes automatically', 'It is only for the wealthy'],
      answer: 0, src: 'icivics',
      explain: 'Voting is how the people give their consent and hold leaders accountable — it’s the heart of self-government.',
      eli5: 'Voting is how you hire — and fire — your leaders.' },
    { q: 'How can the Constitution be changed?',
      choices: ['By adding an amendment', 'By a presidential order', 'By a Supreme Court vote alone', 'It can never be changed'],
      answer: 0, src: 'archives',
      explain: 'The Constitution is changed by amendment — a difficult process needing large majorities in Congress and approval by the states. There are 27 amendments.',
      eli5: 'Changing the rulebook takes almost everyone agreeing — and that’s on purpose.' },
    { q: 'The Massachusetts Constitution (1780) is special because…',
      choices: ['It is the oldest written constitution still in use in the world', 'It was written by the President', 'It created the U.S. Congress', 'It has no amendments'],
      answer: 0, src: 'mass',
      explain: 'Written mostly by John Adams in 1780, the Massachusetts Constitution is the oldest functioning written constitution in the world and helped inspire the U.S. Constitution.',
      eli5: 'Massachusetts wrote the beta version — and it still runs today.' }
  ],

  // =====================================================================
  // GAME 3 — WORLD GOVERNMENTS: match a country to its type of government.
  // Types are simplified for grade 8 but based on the CIA World Factbook.
  // =====================================================================
  // `oneLiner` is the short summary shown under each answer choice in the
  // World Governments game — a quick reminder of what the type means.
  GOVTYPES: {
    'Federal Republic':        { icon: '🏛️', desc: 'People elect representatives, and power is shared between a national government and states or regions.',
                                 oneLiner: 'Elected leaders share power between the nation and its states.',
                                 eli5: 'You elect people to run things, and power is split between the whole country and its states.' },
    'Constitutional Monarchy': { icon: '👑', desc: 'A king or queen is head of state, but elected leaders and a constitution actually run the government.',
                                 oneLiner: 'A king or queen reigns, but elected leaders actually govern.',
                                 eli5: 'There’s a king or queen, but they’re mostly for show — elected leaders do the real work.' },
    'Parliamentary Democracy': { icon: '🗳️', desc: 'Voters elect a parliament, which chooses a prime minister to lead the government.',
                                 oneLiner: 'Voters elect a parliament, which then chooses a leader.',
                                 eli5: 'You vote for the class, and then the class picks the class president.' },
    'Absolute Monarchy':       { icon: '👑', desc: 'A king or royal family holds nearly all the power, with few limits.',
                                 oneLiner: 'A king or royal family holds nearly all the power.',
                                 eli5: 'The king’s word IS the law.' },
    'One-Party State':         { icon: '⭐', desc: 'A single political party controls the government, and no real opposition is allowed.',
                                 oneLiner: 'One party controls the government; no real opposition is allowed.',
                                 eli5: 'Only one team is allowed to play — and it always wins.' },
    'Direct Democracy':        { icon: '🙋', desc: 'Citizens vote directly on many laws themselves, not just for representatives.',
                                 oneLiner: 'Citizens vote directly on laws themselves, not just for reps.',
                                 eli5: 'No middlemen — the people vote on the rules themselves.' },
    'Theocratic Republic':     { icon: '🕌', desc: 'Elected officials share power with religious leaders, and religious law shapes the government.',
                                 oneLiner: 'Elected officials share power with religious leaders.',
                                 eli5: 'Religious leaders get the final say — even over the elected ones.' },
    'Presidential Republic':   { icon: '🗽', desc: 'Citizens directly elect a powerful president who leads the government, separate from an elected parliament.',
                                 oneLiner: 'Citizens directly elect a strong president who runs the government.',
                                 eli5: 'You vote directly for the boss, instead of a group choosing them for you.' },
    'Dominant-Party State':    { icon: '🔁', desc: 'Elections are held and other parties may run, but one leader or party wins almost every time, leaving little real competition for power.',
                                 oneLiner: 'Elections happen, but one party or leader wins almost every time.',
                                 eli5: 'It looks like a real game, but the same team always wins.' }
  },
  // `structure` adds detail on daily operation, `pros`/`cons` weigh how that
  // structure works in practice, `history` covers origins/rule, and
  // `trajectory.dir` (up/down/mixed) + `.text` cover where things are headed —
  // grounded in Freedom House trend data (see SOURCES.freedom).
  GOV_COUNTRIES: [
    { name: 'United States', flag: '🇺🇸', type: 'Federal Republic', head: 'President',
      fact: 'A federal republic of 50 states. Citizens elect a President and members of Congress; power is split by federalism and checks and balances.',
      structure: 'Power is divided among the federal government and 50 states, and split further into three branches at each level. The President is elected every 4 years and Congress every 2 years (House) or on staggered 6-year terms (Senate).',
      pros: ['Strong checks and balances limit any one leader’s power', 'A free press and independent courts can challenge government decisions', 'Peaceful transfers of power have continued for over 200 years'],
      cons: ['The two-party system can make it hard for other views to be heard', 'Federal and state laws sometimes conflict and cause confusion', 'Campaigns and elections are very expensive to run'],
      history: 'The U.S. declared independence from Britain in 1776, and its 1787 Constitution is the oldest written national constitution still in use. Voting and civil rights have expanded over time — through amendments and laws — to enslaved people (1865), women (1920), and other groups once excluded.',
      trajectory: { dir: 'mixed', text: 'Freedom House still rates the U.S. as a free country with strong civil liberties, though its score has slipped somewhat amid rising political polarization; economically it remains one of the world’s largest and most innovative economies.' } },
    { name: 'United Kingdom', flag: '🇬🇧', type: 'Constitutional Monarchy', head: 'Monarch + Prime Minister',
      fact: 'A king or queen is the head of state, but an elected Parliament and a Prime Minister actually govern. The UK has no single written constitution.',
      structure: 'Parliament has an elected House of Commons and an unelected House of Lords. The Prime Minister leads whichever party (or coalition) can command a majority in the Commons, rather than being elected directly by the whole country.',
      pros: ['A long, stable tradition of peaceful transfers of power', 'The monarch offers a nonpolitical symbol of national unity', 'Parliament can act quickly with no separate presidential veto to work around'],
      cons: ['No single written constitution makes some rules harder to pin down', 'The unelected House of Lords limits how directly citizens shape all laws', 'A hereditary monarchy is not something citizens ever vote for'],
      history: 'The UK’s democracy grew slowly over centuries as power shifted from monarchs to Parliament — the Magna Carta (1215) began limiting royal power, and voting rights expanded greatly in the 1800s and 1900s. It once ruled a global empire that has since become a voluntary Commonwealth of independent nations.',
      trajectory: { dir: 'up', text: 'The UK is rated as one of the world’s most free countries by Freedom House, with strong civil liberties and a free press; its economy remains among the largest in the world despite adjustments after leaving the European Union in 2020.' } },
    { name: 'Japan', flag: '🇯🇵', type: 'Constitutional Monarchy', head: 'Emperor + Prime Minister',
      fact: 'The Emperor is a symbol of the nation with no political power; the elected Diet (parliament) and Prime Minister run the government.',
      structure: 'The Diet (parliament) has two houses, and the majority party or coalition in the lower house chooses the Prime Minister. Japan’s 1947 constitution, written after World War II, limits its military to self-defense.',
      pros: ['Stable, peaceful elections have continued since 1947', 'Strong rule of law and very low corruption', 'The constitution strongly protects civil liberties'],
      cons: ['One party has governed for most of the last 70 years, limiting real competition', 'The Emperor’s ceremonial role can blur lines for some citizens', 'Women remain underrepresented in the Diet compared to many democracies'],
      history: 'Japan was ruled by emperors and shoguns for centuries before opening to the world in the mid-1800s. After its defeat in World War II, the U.S. helped Japan write a new democratic constitution in 1947 that turned the Emperor into a symbolic figurehead.',
      trajectory: { dir: 'up', text: 'Freedom House rates Japan as free with strong rights protections; its economy is one of the largest in the world, though it faces long-term challenges from an aging, shrinking population.' } },
    { name: 'Saudi Arabia', flag: '🇸🇦', type: 'Absolute Monarchy', head: 'King',
      fact: 'A king from the Al Saud family holds almost all power. There is no elected national legislature and no constitution like the U.S. one.',
      structure: 'There is no elected national legislature — the King rules by decree, advised by an appointed Consultative Assembly (Shura Council) and religious scholars. Islamic law (Sharia) forms the basis of the legal system.',
      pros: ['Decisions can be made and carried out quickly without lengthy debates', 'Political stability has continued for decades under one ruling family', 'Oil wealth has funded major public projects and services'],
      cons: ['Citizens cannot vote for their national government or change leaders', 'Political parties and public criticism of the monarchy are not allowed', 'Women’s rights and free expression have historically been very limited'],
      history: 'The modern Saudi state was founded in 1932 by King Abdulaziz Al Saud after decades of conflict unifying the Arabian Peninsula. The Al Saud family has ruled ever since, with power passing among the king’s sons and grandsons.',
      trajectory: { dir: 'mixed', text: 'Freedom House still rates Saudi Arabia as “not free,” but recent reforms — like allowing women to drive (2018) and loosening some social restrictions — mark gradual change, even as political rights stay tightly restricted; the economy is being diversified beyond oil under a long-term plan called Vision 2030.' } },
    { name: 'China', flag: '🇨🇳', type: 'One-Party State', head: 'President (Party leader)',
      fact: 'The Chinese Communist Party controls the government. Opposition parties are not allowed to compete for power.',
      structure: 'The Communist Party controls the government, military, and courts; the National People’s Congress formally passes laws but mostly approves decisions party leaders already made. Local governments carry out national policy with some regional variation.',
      pros: ['Long-term planning is possible without frequent election-driven changes', 'Rapid infrastructure and economic development over the past 40 years', 'National policies can be carried out consistently across a huge country'],
      cons: ['Citizens cannot choose their national leaders or form opposing parties', 'The internet and media are closely censored and monitored', 'Public criticism of the government can lead to serious punishment'],
      history: 'China’s imperial dynasties ruled for over 2,000 years until 1912. After decades of civil war, the Communist Party won control in 1949 and has governed ever since, shifting from strict state-controlled economics toward market reforms starting in the late 1970s.',
      trajectory: { dir: 'mixed', text: 'Freedom House rates China as “not free” with tightly controlled political rights; economically it has lifted hundreds of millions out of poverty since the 1980s, though growth has slowed and government control over business has tightened in recent years.' } },
    { name: 'Germany', flag: '🇩🇪', type: 'Federal Republic', head: 'Chancellor',
      fact: 'A federal republic where voters elect a parliament (the Bundestag), which chooses a Chancellor. Power is shared with 16 states.',
      structure: 'The Bundestag (parliament) is elected through a mix of direct and proportional voting, and its majority chooses the Chancellor. Sixteen states (Länder) run their own schools, policing, and other local matters under federalism.',
      pros: ['Proportional voting lets smaller parties be represented', 'Strong constitutional protections built after learning from its Nazi-era past', 'Federalism balances national unity with local control'],
      cons: ['Coalition governments (multiple parties sharing power) can be slow to form', 'The Chancellor is chosen by parliament, not voted for directly by citizens', 'Reunifying East and West Germany’s economies took decades and huge investment'],
      history: 'Germany was a fragmented collection of kingdoms until unifying in 1871, then endured two world wars and, after 1945, split into democratic West Germany and communist East Germany. The two reunified peacefully in 1990 after the Berlin Wall fell in 1989.',
      trajectory: { dir: 'up', text: 'Freedom House rates Germany as one of the freest countries in the world; it has one of Europe’s largest economies, though it faces challenges from an aging population and the costs of shifting to cleaner energy.' } },
    { name: 'India', flag: '🇮🇳', type: 'Federal Republic', head: 'Prime Minister',
      fact: 'The world’s most populous democracy — a federal republic with a parliament and states, guided by a written constitution from 1950.',
      structure: 'Parliament has two houses; the directly elected lower house (Lok Sabha) majority chooses the Prime Minister. States have their own elected governments, and India recognizes 22 official languages.',
      pros: ['The world’s largest democracy, with hundreds of millions of voters', 'A free press and independent courts can check government power', 'Enormous religious and cultural diversity is represented in government'],
      cons: ['Elections are extremely expensive and logistically difficult to run', 'Corruption and bureaucracy can slow government action', 'Religious and caste tensions sometimes affect political life'],
      history: 'India was ruled by various empires and, from the 1800s, by the British, before winning independence in 1947 through a movement led by figures like Mahatma Gandhi. It adopted one of the world’s longest written constitutions in 1950.',
      trajectory: { dir: 'mixed', text: 'Freedom House now rates India as only “partly free,” citing concerns about press freedom and treatment of religious minorities in recent years; economically, though, India is one of the fastest-growing large economies in the world.' } },
    { name: 'Sweden', flag: '🇸🇪', type: 'Constitutional Monarchy', head: 'Monarch + Prime Minister',
      fact: 'A king serves as a ceremonial head of state, while an elected parliament (Riksdag) and Prime Minister make the decisions.',
      structure: 'The Riksdag (parliament) is elected by proportional representation, and its majority or coalition selects the Prime Minister. Sweden has a long tradition of consensus-building among multiple political parties.',
      pros: ['A strong social safety net funded by taxes supports healthcare and education', 'High transparency and very low corruption', 'Consistently ranks among the most free and equal societies in the world'],
      cons: ['High taxes to fund public programs can be a political flashpoint', 'Multi-party coalitions can take a long time to negotiate', 'A hereditary monarchy remains head of state, even with no political power'],
      history: 'Sweden has been a monarchy for over a thousand years, but gradually transferred real power to an elected parliament, becoming a full democracy by the early 1900s. It stayed neutral in most wars, including both World Wars, until joining NATO in 2024.',
      trajectory: { dir: 'up', text: 'Freedom House rates Sweden as one of the most free countries in the world; its economy is stable and prosperous, combining free markets with strong public services.' } },
    { name: 'Switzerland', flag: '🇨🇭', type: 'Direct Democracy', head: 'Federal Council',
      fact: 'Famous for direct democracy: citizens often vote directly on laws and changes through frequent referendums.',
      structure: 'A seven-member Federal Council governs together, with the presidency rotating yearly among its members instead of one powerful leader. Citizens can force a public vote (referendum) on most new national laws just by collecting enough signatures.',
      pros: ['Citizens have unusually direct power over their own laws', 'Power-sharing among the Federal Council avoids any one leader dominating', 'Strong local (canton) control lets regions govern themselves'],
      cons: ['Frequent referendums mean voting can be required many times a year', 'Reaching agreement among many parties and cantons can slow big changes', 'Women didn’t gain the right to vote in national elections until 1971'],
      history: 'Switzerland traces its roots to an alliance of small regions (cantons) formed in 1291 to resist outside rulers. It has stayed neutral in international conflicts, including both World Wars, for over 200 years.',
      trajectory: { dir: 'up', text: 'Freedom House rates Switzerland among the most free nations in the world; it has one of the highest standards of living and most stable economies globally.' } },
    { name: 'Iran', flag: '🇮🇷', type: 'Theocratic Republic', head: 'Supreme Leader + President',
      fact: 'Voters elect a president and parliament, but a religious Supreme Leader and clerics hold the highest power under Islamic law.',
      structure: 'Iran has an elected president and parliament, but a religious Supreme Leader — chosen by a council of clerics, not the public — holds final authority over the military, courts, and major policies. An unelected Guardian Council can disqualify candidates before elections happen.',
      pros: ['Elected offices give citizens some limited voice in choosing officials', 'Religious guidance is intended to keep laws aligned with the majority faith’s values', 'The system has provided decades of continuity since 1979'],
      cons: ['The unelected Supreme Leader and Guardian Council can override elected officials', 'Candidates who disagree with the ruling system are often barred from running', 'Protests and free expression are frequently restricted'],
      history: 'Iran was ruled by a monarchy (the Shah) until the 1979 Islamic Revolution replaced it with the current system, combining elected institutions with rule by religious clerics under a Supreme Leader.',
      trajectory: { dir: 'down', text: 'Freedom House rates Iran as “not free,” and recent years have seen large protests over women’s rights and economic hardship met with government crackdowns; international sanctions have also strained its economy.' } },
    { name: 'North Korea', flag: '🇰🇵', type: 'One-Party State', head: 'Supreme Leader',
      fact: 'One family and one party have ruled since 1948. Elections offer no real choice, and citizens have very few freedoms.',
      structure: 'The Workers’ Party of Korea, led by the Kim family, controls every level of government, the military, and the economy. A parliament exists, but only party-approved candidates run and results are not competitive.',
      pros: ['The government guarantees state-assigned jobs and basic housing', 'Highly centralized control lets the state mobilize large projects quickly', 'Leadership continuity has kept the same family in power for three generations'],
      cons: ['Citizens cannot vote in real competitive elections or criticize leaders', 'The state controls nearly all information, media, and internet access', 'Chronic food and resource shortages have affected the population for decades'],
      history: 'Korea was divided into North and South after World War II in 1945. Kim Il Sung founded North Korea in 1948, and his family — now led by his grandson, Kim Jong Un — has ruled continuously since.',
      trajectory: { dir: 'down', text: 'Freedom House rates North Korea as one of the least free countries in the world, with almost no political rights or civil liberties, and its economy remains isolated and struggling under international sanctions.' } },
    { name: 'Canada', flag: '🇨🇦', type: 'Constitutional Monarchy', head: 'Monarch + Prime Minister',
      fact: 'A parliamentary democracy AND a constitutional monarchy: the British monarch is head of state, but an elected Prime Minister governs.',
      structure: 'Parliament is elected, and the party with a majority (or the most seats) chooses the Prime Minister; the British monarch’s representative (the Governor General) plays a ceremonial role. Provinces have significant control over healthcare, education, and natural resources.',
      pros: ['A Charter of Rights and Freedoms (1982) constitutionally protects civil liberties', 'Provinces can tailor policy to their own populations and needs', 'Consistently rated among the most free and stable democracies'],
      cons: ['The Prime Minister isn’t directly elected by the whole country, only chosen through local races and party rules', 'Relations between the federal government and French-speaking Quebec have sometimes been tense', 'A hereditary foreign monarch remains the ceremonial head of state'],
      history: 'Canada formed as a self-governing dominion within the British Empire in 1867 and gradually gained full independence, formalized when it patriated its constitution in 1982. It has long balanced English- and French-speaking populations and Indigenous nations’ rights.',
      trajectory: { dir: 'up', text: 'Freedom House rates Canada as one of the most free countries in the world; its economy is stable and resource-rich, though it continues working to address the historical treatment of Indigenous peoples.' } },
    { name: 'France', flag: '🇫🇷', type: 'Presidential Republic', head: 'President',
      fact: 'A republic where citizens directly elect a President and a National Assembly. (Unlike the U.S., it is not federal — power is more central.)',
      structure: 'France’s president is directly elected by the public and shares power with a Prime Minister and National Assembly; unlike the U.S., power is not divided among strong regional states. The president can dissolve the Assembly and call new elections.',
      pros: ['The president is elected directly by citizens, not just by an assembly', 'A strong central government can act decisively during emergencies', 'Robust protections for free speech and secular government (laïcité)'],
      cons: ['Centralized power means less regional (state-level) authority than federal systems', 'Frequent large protests suggest some feel underrepresented between elections', '“Cohabitation” — a president and prime minister from opposing parties — can cause gridlock'],
      history: 'France’s monarchy was overthrown in the French Revolution (1789), leading to over a century of shifting republics, empires, and monarchies before the current Fifth Republic was established in 1958 under President Charles de Gaulle.',
      trajectory: { dir: 'mixed', text: 'Freedom House rates France as free with strong rights protections, though recent years have seen political polarization and large protests over economic policy; it remains one of the world’s largest economies.' } },
    { name: 'Brazil', flag: '🇧🇷', type: 'Federal Republic', head: 'President',
      fact: 'A federal republic of 26 states, where citizens elect a President and Congress. Voting is required by law for most adults.',
      structure: 'Brazil’s president is directly elected and leads a federal system of 26 states plus a federal district, similar in structure to the United States. Voting is required by law for most adults between 18 and 70.',
      pros: ['Mandatory voting leads to very high voter turnout', 'A federal system lets diverse regions have local control', 'A young democracy has shown resilience after past military rule'],
      cons: ['Political corruption scandals have repeatedly shaken public trust', 'Deep economic inequality remains a major challenge', 'Democratic institutions have faced serious stress tests around recent elections'],
      history: 'Brazil was a Portuguese colony until independence in 1822, later became a republic in 1889, and was ruled by a military dictatorship from 1964 to 1985 before returning to democracy with a new constitution in 1988.',
      trajectory: { dir: 'mixed', text: 'Freedom House rates Brazil as free, but notes strain on democratic institutions around the disputed 2022 election period; the economy is one of the largest in Latin America but faces ongoing inequality and Amazon deforestation concerns.' } },
    { name: 'Spain', flag: '🇪🇸', type: 'Constitutional Monarchy', head: 'Monarch + Prime Minister',
      fact: 'A king is head of state, but an elected parliament (Cortes) and a Prime Minister run the country under a 1978 constitution.',
      structure: 'Spain’s parliament (Cortes Generales) is elected and its majority chooses the Prime Minister, while the king serves a ceremonial role as head of state. Spain is divided into 17 autonomous regions with varying self-government, including Catalonia and the Basque Country.',
      pros: ['Strong regional autonomy lets diverse cultures and languages govern locally', 'Its peaceful transition from dictatorship to democracy is seen as a model for other countries', 'Free press and fair elections have been stable since the 1970s'],
      cons: ['Regional independence movements (like in Catalonia) have caused political tension', 'Coalition governments can be difficult to form and keep stable', 'Youth unemployment has remained high compared to other European countries'],
      history: 'Spain was ruled by the dictator Francisco Franco from 1939 to 1975. After his death, the country peacefully transitioned to a democratic constitutional monarchy, adopting its current constitution in 1978.',
      trajectory: { dir: 'up', text: 'Freedom House rates Spain as free with strong civil liberties; its economy has recovered significantly since the 2008 financial crisis, though regional independence tensions remain unresolved.' } },
    { name: 'Australia', flag: '🇦🇺', type: 'Constitutional Monarchy', head: 'Monarch + Prime Minister',
      fact: 'A parliamentary democracy and constitutional monarchy where voting is compulsory — citizens can be fined for not voting.',
      structure: 'Parliament is elected and its majority chooses the Prime Minister, while the British monarch’s representative (the Governor-General) holds a mostly ceremonial role. Voting is compulsory for citizens 18 and older, and ranked-choice voting is used in many elections.',
      pros: ['Compulsory voting leads to very high election turnout', 'Strong, stable democratic institutions with peaceful transfers of power', 'Ranked-choice voting lets citizens express more detailed preferences than a single vote'],
      cons: ['Citizens can be fined for not voting, which some see as limiting personal choice', 'A hereditary foreign monarch remains the ceremonial head of state', 'Indigenous Australians were left out of the original constitution and still face rights debates today'],
      history: 'Australia began as British penal and settler colonies starting in 1788, home to Aboriginal and Torres Strait Islander peoples for tens of thousands of years before that. The colonies federated into one country in 1901 while remaining part of the British Commonwealth.',
      trajectory: { dir: 'up', text: 'Freedom House rates Australia as one of the most free countries in the world; its economy is stable and resource-rich, though debates continue over constitutional recognition and rights for Indigenous Australians.' } },
    { name: 'Mexico', flag: '🇲🇽', type: 'Federal Republic', head: 'President',
      fact: 'A federal republic of 31 states plus Mexico City. Citizens elect a President to one 6-year term (no re-election) and a Congress.',
      structure: 'Power is split between the national government and 31 states, each with its own governor and local congress, similar to the U.S. system. For 71 years (1929–2000), one party won every presidential election before Mexico became a fully competitive multi-party democracy.',
      pros: ['Federalism lets diverse states and regions govern themselves', 'Peaceful transfers of power between different parties are now the norm', 'A single 6-year term with no re-election keeps any one president from staying too long'],
      cons: ['Drug cartel violence has challenged the rule of law in many regions', 'Corruption remains a serious concern at multiple levels of government', 'No re-election means voters can’t keep a president accountable by re-electing or rejecting them'],
      history: 'Mexico won independence from Spain in 1821 after a long war, followed by decades of instability and the Mexican Revolution (1910–1920), which shaped its current constitution. One party then dominated politics for most of the 20th century until opposition parties began winning major elections in 2000.',
      trajectory: { dir: 'mixed', text: 'Freedom House rates Mexico as only “partly free,” citing violence against journalists and organized crime’s influence on politics; its economy is one of the largest in Latin America and closely tied to trade with the United States.' } },
    { name: 'Italy', flag: '🇮🇹', type: 'Parliamentary Democracy', head: 'President + Prime Minister',
      fact: 'A parliamentary republic where a mostly ceremonial President appoints a Prime Minister who must have the support of Parliament.',
      structure: 'Parliament is elected and its majority — often a coalition of several parties — chooses the Prime Minister, who runs the government day-to-day. Italy has had over 60 different governments since World War II, more than almost any other democracy.',
      pros: ['Proportional voting gives smaller parties a real voice in Parliament', 'A largely ceremonial president provides stability above day-to-day politics', 'Regions have meaningful control over local affairs'],
      cons: ['Frequent changes of government can make long-term planning difficult', 'Coalitions of many parties can be unstable and hard to hold together', 'Political corruption scandals have repeatedly shaken public trust'],
      history: 'Italy unified into one country in 1861 after centuries as separate kingdoms and city-states. It became a republic in 1946 after voters chose to abolish the monarchy following Benito Mussolini’s fascist dictatorship and World War II.',
      trajectory: { dir: 'mixed', text: 'Freedom House rates Italy as free with strong civil liberties, though frequent government turnover and concerns about press ownership are noted; it has the third-largest economy in the European Union.' } },
    { name: 'South Korea', flag: '🇰🇷', type: 'Presidential Republic', head: 'President',
      fact: 'A presidential republic where citizens directly elect a president to a single 5-year term, separate from an elected National Assembly.',
      structure: 'The president leads the executive branch and cannot be re-elected after one 5-year term, a rule meant to prevent any leader from holding power too long. The National Assembly is separately elected and can act as a check on the president.',
      pros: ['A single-term limit prevents any president from staying in power too long', 'Rapid economic growth has dramatically lifted living standards since the 1960s', 'A vibrant free press and active civil society hold leaders accountable'],
      cons: ['A one-term limit means voters can’t re-elect a president they like', 'Political parties are often divided by intense, personal rivalries', 'Past presidents have frequently faced corruption investigations after leaving office'],
      history: 'Korea was divided after World War II, and South Korea was ruled by a series of authoritarian and military governments for decades before mass protests led to full democratic elections starting in 1987. Since then, it has become one of Asia’s most vibrant democracies.',
      trajectory: { dir: 'up', text: 'Freedom House rates South Korea as free with strong civil liberties; its economy has grown from one of the poorest in the world after the Korean War to one of the most advanced, though it faces a very low birth rate and tensions with North Korea.' } },
    { name: 'Russia', flag: '🇷🇺', type: 'Dominant-Party State', head: 'President',
      fact: 'A federation on paper, with a president, prime minister, and parliament, but real power is concentrated around one long-serving president and his allies.',
      structure: 'Elections are held for president and parliament, and multiple parties are legally allowed to run. In practice, one leader and his party have controlled the presidency and most of parliament for over two decades, and independent challengers face major obstacles.',
      pros: ['A single, consistent leadership has provided political stability for over 20 years', 'Rich natural resources like oil and gas fund significant government spending', 'Elections and multiple parties still formally exist, unlike a strict one-party state'],
      cons: ['Independent media and real political opposition face serious restrictions', 'Elections are widely viewed as not being genuinely free or fair', 'International sanctions since 2022 have significantly strained the economy'],
      history: 'Russia was ruled by tsars (emperors) for centuries, then became the center of the communist Soviet Union after the 1917 revolution. The Soviet Union collapsed in 1991, and Russia became a struggling new democracy before power gradually concentrated around one leader starting in the early 2000s.',
      trajectory: { dir: 'down', text: 'Freedom House rates Russia as “not free,” noting a steady decline in political rights and press freedom over the past two decades; its economy has also been squeezed by international sanctions following its 2022 invasion of Ukraine.' } },
    { name: 'Nigeria', flag: '🇳🇬', type: 'Federal Republic', head: 'President',
      fact: 'Africa’s most populous country and a federal republic of 36 states, where citizens elect a President and a two-house National Assembly.',
      structure: 'Power is shared between the national government and 36 states, each with an elected governor, echoing the U.S. federal model. Nigeria returned to civilian, elected rule in 1999 after decades of on-and-off military governments.',
      pros: ['Federalism lets Nigeria’s many ethnic and religious groups have a local voice', 'Civilian democratic rule has continued without interruption since 1999', 'A free, outspoken press and film industry (Nollywood) are influential across Africa'],
      cons: ['Corruption and mismanagement of oil wealth remain major challenges', 'Armed groups and violence in some regions strain government control', 'Wide economic inequality persists despite the country’s oil riches'],
      history: 'Nigeria was a British colony until independence in 1960, then experienced a civil war (1967–1970) and a series of military coups and governments. It has been a continuous civilian democracy since 1999, the longest stretch in its history.',
      trajectory: { dir: 'mixed', text: 'Freedom House rates Nigeria as only “partly free,” citing corruption and security challenges from armed groups; it has one of Africa’s largest economies, driven heavily by oil, and a young, fast-growing population.' } },
    { name: 'Egypt', flag: '🇪🇬', type: 'Presidential Republic', head: 'President',
      fact: 'A presidential republic where an elected president holds broad power over the government, military, and courts.',
      structure: 'The president is elected by popular vote and appoints the prime minister and cabinet; the military has historically played a very influential role in choosing and supporting the country’s leaders. Parliament is elected but has limited power to check the president.',
      pros: ['A strong central government has kept the country’s territory stable for decades', 'Egypt controls the strategically vital Suez Canal, a major source of national revenue', 'Rich ancient history and heritage sites make it a major hub for tourism and culture'],
      cons: ['Political opposition and independent media face significant restrictions', 'The military’s deep influence limits how much power elected civilians truly hold', 'Economic struggles, including high inflation, have burdened many citizens'],
      history: 'Egypt has one of the world’s oldest civilizations, later ruled by various empires before becoming a British-influenced kingdom and then a republic after a 1952 military coup. It has been led by a series of presidents, often with strong military backing, ever since — including large protests in 2011 that briefly ousted a long-ruling president.',
      trajectory: { dir: 'down', text: 'Freedom House rates Egypt as “not free,” citing restrictions on speech, protest, and political opposition since 2013; the economy has faced serious strain from high debt and inflation despite ongoing international loan support.' } },
    { name: 'Israel', flag: '🇮🇱', type: 'Parliamentary Democracy', head: 'President + Prime Minister',
      fact: 'A parliamentary democracy where the Knesset (parliament) is elected by proportional representation and its majority coalition chooses the Prime Minister.',
      structure: 'Israel has no single written constitution, relying instead on a set of “Basic Laws.” Because proportional representation lets many small parties win seats, governments are almost always multi-party coalitions.',
      pros: ['Proportional representation gives even small parties and viewpoints a voice', 'A vibrant free press and independent judiciary provide strong checks on power', 'Regular, competitive elections have continued since the country’s founding in 1948'],
      cons: ['Coalition governments made of many small parties can be unstable', 'No single written constitution means some rules are open to dispute', 'Ongoing conflict with Palestinians and neighbors shapes and strains politics'],
      history: 'The modern state of Israel was founded in 1948 as a homeland for the Jewish people after centuries of displacement and, more recently, the Holocaust. It has been a parliamentary democracy since its founding, though it remains in a long-running and unresolved conflict over land and statehood with Palestinians and some neighboring states.',
      trajectory: { dir: 'mixed', text: 'Freedom House rates Israel as free for its own citizens, while rating the Palestinian territories very differently; ongoing conflict and recent debates over the courts’ power have raised questions about the country’s democratic institutions.' } },
    { name: 'South Africa', flag: '🇿🇦', type: 'Parliamentary Democracy', head: 'President',
      fact: 'A parliamentary republic where the National Assembly, elected by proportional representation, chooses the President, who then leads the government.',
      structure: 'Unlike many parliamentary systems, South Africa’s President is both head of state and head of government — there is no separate Prime Minister. Since ending apartheid, South Africa has held regular multi-party elections open to all races.',
      pros: ['One of the most progressive constitutions in the world, with strong equality protections', 'Free, multiracial elections have continued since apartheid ended in 1994', 'An independent judiciary has shown willingness to check the government'],
      cons: ['Deep economic inequality inherited from apartheid remains a major challenge', 'One party has won every national election since 1994, though its majority has recently shrunk', 'Frequent power outages and public service problems have strained the government’s reputation'],
      history: 'South Africa was ruled under apartheid, a system of strict racial segregation, from 1948 to 1994. Mass protests, international pressure, and negotiations led by leaders like Nelson Mandela ended apartheid and brought the country’s first fully democratic elections in 1994.',
      trajectory: { dir: 'mixed', text: 'Freedom House rates South Africa as free with strong constitutional protections, though it flags corruption and inequality as ongoing concerns; the economy remains one of Africa’s largest but continues to face high unemployment.' } },
    { name: 'Indonesia', flag: '🇮🇩', type: 'Presidential Republic', head: 'President',
      fact: 'The world’s largest Muslim-majority country and a presidential republic where citizens directly elect a president across a nation of over 17,000 islands.',
      structure: 'The president is directly elected and leads the executive branch, while an elected legislature makes laws; power is shared with elected local governments across the country’s many islands and regions. Indonesia has held peaceful, competitive presidential elections since becoming a democracy in the late 1990s.',
      pros: ['A young democracy has held peaceful elections and transfers of power since 1998', 'Local governments have real authority to manage their own diverse regions', 'One of the largest and fastest-growing economies in Southeast Asia'],
      cons: ['Corruption remains a significant challenge at multiple levels of government', 'Religious and ethnic tensions occasionally affect politics in a very diverse nation', 'Governing thousands of scattered islands makes consistent administration difficult'],
      history: 'Indonesia was a Dutch colony for centuries before declaring independence in 1945. It was ruled by an authoritarian military-backed government under President Suharto from 1967 to 1998, when mass protests forced him to resign and led to today’s democracy.',
      trajectory: { dir: 'mixed', text: 'Freedom House rates Indonesia as only “partly free,” citing corruption and pressure on free expression; its economy is one of the fastest-growing in the world, powered by a large, young population.' } },
    { name: 'Singapore', flag: '🇸🇬', type: 'Dominant-Party State', head: 'Prime Minister',
      fact: 'A parliamentary republic where one political party, the People’s Action Party, has won every election and led the government since 1959.',
      structure: 'Parliament is elected and its majority chooses the Prime Minister, following a parliamentary structure similar to the UK’s. Elections are competitive and other parties are legally allowed to run, but strict laws on speech and media make it very difficult for opposition parties to challenge the dominant party.',
      pros: ['Decades of stable, consistent leadership have helped fuel rapid economic growth', 'Extremely low corruption and highly efficient public services', 'Multiple parties are legally allowed to run, unlike a strict one-party state'],
      cons: ['Strict laws on speech and the press make it hard for opposition voices to be heard', 'One party has held power continuously for over 60 years with no real turnover', 'Government lawsuits against critics have drawn international criticism'],
      history: 'Singapore was a British colony and briefly part of Malaysia before becoming a fully independent country in 1965. Founding leader Lee Kuan Yew and his People’s Action Party built it from a small, poor port city into one of the world’s wealthiest nations, while keeping tight control over politics and the press.',
      trajectory: { dir: 'mixed', text: 'Freedom House rates Singapore as only “partly free,” citing limits on political competition and free expression; economically, it is one of the wealthiest and most developed countries in the world.' } }
  ],

  // =====================================================================
  // GAME 4 — YOUR RIGHTS: a right protected in the U.S., which amendment
  // protects it, and how the SAME right looks in other countries.
  // =====================================================================
  RIGHTS: [
    { right: 'Freedom of Speech', icon: '🗣️', amendment: '1st Amendment',
      us: 'You can speak, write, and share opinions — even criticize the government — without being punished by the government.',
      eli5: 'You can say the government is doing a bad job — out loud — and not get arrested for it.',
      world: [
        { country: 'Norway', flag: '🇳🇴', status: 'strong', note: 'Among the freest in the world for speech and press.' },
        { country: 'China', flag: '🇨🇳', status: 'restricted', note: 'The government censors the internet and punishes public criticism.' },
        { country: 'North Korea', flag: '🇰🇵', status: 'restricted', note: 'Almost no free speech; criticizing leaders can bring harsh punishment.' }
      ] },
    { right: 'Freedom of Religion', icon: '🕊️', amendment: '1st Amendment',
      us: 'You can follow any religion, or none at all, and the government cannot set up an official national religion.',
      eli5: 'You pick your own beliefs — the government doesn’t pick them for you.',
      world: [
        { country: 'Canada', flag: '🇨🇦', status: 'strong', note: 'Religious freedom is protected by its Charter of Rights.' },
        { country: 'Saudi Arabia', flag: '🇸🇦', status: 'restricted', note: 'Public worship of other religions is heavily restricted.' },
        { country: 'Iran', flag: '🇮🇷', status: 'restricted', note: 'Religious law shapes the state and limits some faiths.' }
      ] },
    { right: 'Freedom of the Press', icon: '📰', amendment: '1st Amendment',
      us: 'Newspapers, TV, and websites can report the news and criticize leaders without government control.',
      eli5: 'Reporters can tell the truth even when leaders don’t like it.',
      world: [
        { country: 'Sweden', flag: '🇸🇪', status: 'strong', note: 'One of the first nations to protect press freedom, back in 1766.' },
        { country: 'Germany', flag: '🇩🇪', status: 'strong', note: 'A free and independent press is protected by law.' },
        { country: 'North Korea', flag: '🇰🇵', status: 'restricted', note: 'All news is controlled by the state.' }
      ] },
    { right: 'Right to Peaceful Assembly', icon: '🪧', amendment: '1st Amendment',
      us: 'You can gather and protest peacefully, and ask the government to fix problems (petition).',
      eli5: 'You and your friends can gather with signs to say something’s unfair.',
      world: [
        { country: 'France', flag: '🇫🇷', status: 'strong', note: 'Public protest is a well-known part of French political life.' },
        { country: 'China', flag: '🇨🇳', status: 'restricted', note: 'Large unapproved protests are usually broken up.' },
        { country: 'United States', flag: '🇺🇸', status: 'strong', note: 'Protected by the First Amendment.' }
      ] },
    { right: 'Right to Vote', icon: '🗳️', amendment: '15th, 19th & 26th Amendments', img: 'img/voting.webp',
      us: 'Citizens 18 and older can vote. Voting cannot be denied because of race (15th), sex (19th), or age over 18 (26th).',
      eli5: 'Every adult citizen gets a say — no matter their race, sex, or wealth.',
      world: [
        { country: 'Australia', flag: '🇦🇺', status: 'compulsory', note: 'Voting is required by law — you can be fined for not voting.' },
        { country: 'Brazil', flag: '🇧🇷', status: 'compulsory', note: 'Voting is mandatory for most adults.' },
        { country: 'Saudi Arabia', flag: '🇸🇦', status: 'restricted', note: 'There are no national elections for the government.' }
      ] },
    { right: 'Right to a Fair Trial by Jury', icon: '⚖️', amendment: '6th & 7th Amendments', img: 'img/jury.webp',
      us: 'If accused of a crime, you get a speedy, public trial by an impartial jury of citizens, with a lawyer to defend you.',
      eli5: 'If you’re accused, regular people hear your side before anyone can punish you.',
      world: [
        { country: 'United Kingdom', flag: '🇬🇧', status: 'strong', note: 'Jury trials began here centuries ago and are still used for serious crimes.' },
        { country: 'Japan', flag: '🇯🇵', status: 'mixed', note: 'Uses a mix of citizen judges and professional judges (the saiban-in system).' },
        { country: 'China', flag: '🇨🇳', status: 'restricted', note: 'No independent jury system; courts are controlled by the party.' }
      ] },
    { right: 'Protection from Unreasonable Searches', icon: '🔒', amendment: '4th Amendment',
      us: 'Police generally need a warrant from a judge to search your home or belongings.',
      eli5: 'Police can’t dig through your stuff without a judge’s permission slip.',
      world: [
        { country: 'Germany', flag: '🇩🇪', status: 'strong', note: 'Privacy of the home is strongly protected by its Basic Law.' },
        { country: 'China', flag: '🇨🇳', status: 'restricted', note: 'The government runs wide surveillance with few privacy limits.' },
        { country: 'United States', flag: '🇺🇸', status: 'strong', note: 'Protected by the Fourth Amendment.' }
      ] },
    { right: 'Right to Remain Silent (Due Process)', icon: '🤐', amendment: '5th Amendment',
      us: 'You don’t have to testify against yourself, and the government must follow fair legal steps before punishing you.',
      eli5: 'You never have to be a witness against yourself.',
      world: [
        { country: 'Canada', flag: '🇨🇦', status: 'strong', note: 'The Charter protects the right to silence and fair process.' },
        { country: 'India', flag: '🇮🇳', status: 'strong', note: 'The constitution protects against self-incrimination.' },
        { country: 'North Korea', flag: '🇰🇵', status: 'restricted', note: 'Fair legal process is largely absent.' }
      ] },
    { right: 'No Cruel or Unusual Punishment', icon: '🚫', amendment: '8th Amendment',
      us: 'Punishments cannot be cruel or unusual, and bail or fines cannot be excessive.',
      eli5: 'Punishments have to fit the crime — no torture, ever.',
      world: [
        { country: 'Norway', flag: '🇳🇴', status: 'strong', note: 'Prisons focus on rehabilitation; there is no death penalty.' },
        { country: 'Germany', flag: '🇩🇪', status: 'strong', note: 'Human dignity is the first line of its constitution.' },
        { country: 'Saudi Arabia', flag: '🇸🇦', status: 'restricted', note: 'Uses corporal and capital punishments under its legal code.' }
      ] }
  ],

  // =====================================================================
  // GAME 5 — BRANCH SORTER: which branch has this power?
  // =====================================================================
  POWERS: [
    // Legislative
    { icon: '📜', branch: 'legislative', text: 'Makes the nation’s laws',
      why: 'Congress — the House and Senate — writes, debates, and passes federal laws.' },
    { icon: '⚔️', branch: 'legislative', text: 'Declares war',
      why: 'Only Congress can officially declare war, even though the President commands the military.' },
    { icon: '💰', branch: 'legislative', text: 'Controls government spending',
      why: 'Congress holds the “power of the purse” — no federal money can be spent unless Congress approves it.' },
    { icon: '🔁', branch: 'legislative', text: 'Can override a President’s veto',
      why: 'If two-thirds of both houses agree, a bill becomes law even after the President says no.' },
    { icon: '✅', branch: 'legislative', text: 'Confirms Supreme Court justices',
      why: 'The President nominates justices, but the Senate votes to confirm or reject them.' },
    { icon: '🧑‍⚖️', branch: 'legislative', text: 'Can impeach the President',
      why: 'The House can impeach (formally accuse) a President, and the Senate holds the trial.' },
    { icon: '🤝', branch: 'legislative', text: 'Approves treaties with other countries',
      why: 'The President negotiates treaties, but the Senate must approve them by a two-thirds vote.' },
    // Executive
    { icon: '🖋️', branch: 'executive', text: 'Signs bills into law',
      why: 'A bill passed by Congress only becomes law when the President signs it.' },
    { icon: '🚫', branch: 'executive', text: 'Vetoes bills',
      why: 'The President can reject a bill Congress passed and send it back.' },
    { icon: '🎖️', branch: 'executive', text: 'Commands the military',
      why: 'The President is commander-in-chief of the armed forces.' },
    { icon: '🌐', branch: 'executive', text: 'Negotiates treaties',
      why: 'The President and diplomats work out agreements with other countries (which the Senate must then approve).' },
    { icon: '⚖️', branch: 'executive', text: 'Nominates Supreme Court justices',
      why: 'When a seat opens, the President picks the nominee — then the Senate confirms or rejects.' },
    { icon: '👮', branch: 'executive', text: 'Enforces the laws',
      why: 'The executive branch — its agencies, departments, and officers — carries out the laws Congress passes.' },
    { icon: '🕊️', branch: 'executive', text: 'Grants pardons',
      why: 'The President can forgive federal crimes and reduce punishments.' },
    // Judicial
    { icon: '🔍', branch: 'judicial', text: 'Interprets what laws mean',
      why: 'Courts decide how laws apply when people disagree about them.' },
    { icon: '🛑', branch: 'judicial', text: 'Can declare a law unconstitutional',
      why: 'This is judicial review — courts can strike down laws that break the Constitution (established in Marbury v. Madison, 1803).' },
    { icon: '🗺️', branch: 'judicial', text: 'Settles disputes between states',
      why: 'When states disagree — say, over a border or a river — the Supreme Court decides.' },
    { icon: '📤', branch: 'judicial', text: 'Hears appeals from lower courts',
      why: 'Higher courts review lower-court decisions to correct mistakes.' },
    { icon: '✋', branch: 'judicial', text: 'Can rule the President’s actions unconstitutional',
      why: 'Even the President must follow the Constitution — courts can block actions that don’t.' },
    { icon: '🏛️', branch: 'judicial', text: 'Decides cases about federal law',
      why: 'Federal courts hear cases involving the Constitution, federal laws, and treaties.' },
    { icon: '👩‍⚖️', branch: 'judicial', text: 'Presides over a President’s impeachment trial',
      why: 'When a President is tried in the Senate, the Chief Justice of the Supreme Court runs the trial.' }
  ],

  // =====================================================================
  // GAME 6 — ORDER IT!: put the steps in the correct order.
  // =====================================================================
  SEQUENCES: [
    { title: 'How a bill becomes a law', icon: '📄', src: 'congress', dia: 'bill',
      note: 'Fun fact: a bill can actually start in either the House or the Senate (except tax bills, which must start in the House). Both must pass the exact same version.',
      steps: [
        { icon: '💡', text: 'Someone has an idea for a new law', desc: 'Ideas can come from anyone — citizens, groups, or lawmakers.' },
        { icon: '📄', text: 'A member of Congress introduces the bill', desc: 'Only a member of the House or Senate can introduce a bill.' },
        { icon: '🔍', text: 'A committee studies, changes, and votes on the bill', desc: 'Most bills “die” in committee — only the strong survive.' },
        { icon: '🏛️', text: 'The House debates and votes to pass it', desc: 'A majority — more than half — must vote yes.' },
        { icon: '🏛️', text: 'The Senate debates and passes the same version', desc: 'Both chambers must agree on identical text.' },
        { icon: '🖋️', text: 'The President signs the bill — or vetoes it', desc: 'A veto sends it back; Congress can override with a two-thirds vote.' },
        { icon: '⚖️', text: 'It becomes a law of the United States', desc: 'Now the executive branch enforces it and the courts interpret it.' }
      ] },
    { title: 'The founding of American government', icon: '🇺🇸', src: 'archives',
      note: 'Eleven years passed between declaring independence (1776) and writing the Constitution (1787).',
      steps: [
        { icon: '⚔️', text: '1775 — The Revolutionary War begins', desc: 'Fighting breaks out at Lexington and Concord, Massachusetts.' },
        { icon: '🖋️', text: '1776 — The Declaration of Independence', desc: 'The colonies declare they are free from Britain.' },
        { icon: '🕊️', text: '1783 — The war ends', desc: 'Britain recognizes American independence in the Treaty of Paris.' },
        { icon: '🏛️', text: '1787 — The Constitutional Convention', desc: 'Delegates in Philadelphia write the U.S. Constitution.' },
        { icon: '✅', text: '1788 — The states ratify the Constitution', desc: 'New Hampshire is the 9th state to say yes, making it official.' },
        { icon: '📃', text: '1791 — The Bill of Rights is added', desc: 'The first ten amendments protect individual freedoms.' }
      ] },
    { title: 'How the Constitution gets amended', icon: '✏️', src: 'archives',
      note: 'It’s hard on purpose — only 27 amendments have made it in over 230 years.',
      steps: [
        { icon: '✏️', text: 'Someone proposes a change to the Constitution', desc: 'Most amendments start in Congress.' },
        { icon: '🏛️', text: 'Two-thirds of both houses of Congress approve it', desc: 'A very high bar — both the House and the Senate.' },
        { icon: '🗺️', text: 'The proposal is sent to all the states', desc: 'Each state legislature (or convention) votes on it.' },
        { icon: '✅', text: 'Three-fourths of the states ratify it', desc: 'Today that means 38 of the 50 states.' },
        { icon: '📜', text: 'It becomes part of the Constitution', desc: 'It now carries the same force as the original document.' }
      ] }
  ]
};
