// Civics & Government data — aligned to the Massachusetts 2018 HSS Framework,
// Grade 8 "U.S. and Massachusetts Government and Civic Life."
// Content is kept accurate and 8th-grade friendly. Every game's reveal points
// back to a real, citable source listed in SOURCES.
// `eli5` fields are super-simple analogies shown in a "Like you're 5" box.
window.CIVICS = {

  // ---- Sources (shown in the 📚 Sources popup and cited in reveals) ----
  SOURCES: [
    { key: 'ma',        name: 'MA 2018 History & Social Science Framework (Grade 8 Civics)', url: 'https://www.doe.mass.edu/frameworks/hss/2018-12.pdf', note: 'The Massachusetts standards this game is built on.' },
    { key: 'archives',  name: 'U.S. Constitution — National Archives', url: 'https://www.archives.gov/founding-docs/constitution', note: 'Full text of the Constitution and its amendments.' },
    { key: 'bor',       name: 'The Bill of Rights — National Archives', url: 'https://www.archives.gov/founding-docs/bill-of-rights', note: 'The first 10 amendments, in the founders’ own words.' },
    { key: 'doi',       name: 'Declaration of Independence — National Archives', url: 'https://www.archives.gov/founding-docs/declaration', note: 'The 1776 document that declared independence.' },
    { key: 'congress',  name: 'How Our Laws Are Made — Congress.gov', url: 'https://www.congress.gov/help/learn-about-the-legislative-process/how-our-laws-are-made', note: 'The official step-by-step of how a bill becomes a law.' },
    { key: 'usagov',    name: 'How the U.S. Government Is Organized — USA.gov', url: 'https://www.usa.gov/branches-of-government', note: 'Plain-language overview of the three branches.' },
    { key: 'icivics',   name: 'iCivics', url: 'https://www.icivics.org/', note: 'Free civics lessons and games (founded by Justice Sandra Day O’Connor).' },
    { key: 'court',     name: 'About the Supreme Court — U.S. Courts', url: 'https://www.uscourts.gov/about-federal-courts/educational-resources/about-educational-outreach/activity-resources/about', note: 'What the federal courts and Supreme Court do.' },
    { key: 'mass',      name: 'Massachusetts Constitution & Town Meeting — Mass.gov', url: 'https://www.mass.gov/the-massachusetts-state-constitution', note: 'The 1780 state constitution and local town-meeting government.' },
    { key: 'factbook',  name: 'The World Factbook — Government Types', url: 'https://www.cia.gov/the-world-factbook/field/government-type/', note: 'How the government of every country is classified.' },
    { key: 'freedom',   name: 'Freedom House — Freedom in the World', url: 'https://freedomhouse.org/countries/freedom-world/scores', note: 'Yearly ratings of political rights and civil liberties by country.' }
  ],

  // =====================================================================
  // GAME 1 — TERMS: match the civics term to what it means.
  // `def` = the clue shown, `kid` = friendly restatement, `ex` = an example.
  // =====================================================================
  TERMS: [
    { term: 'Legislative Branch', icon: '🏛️', cat: 'branches', img: 'img/capitol.webp',
      def: 'The branch of government that makes the laws.',
      kid: 'Congress — the Senate and the House of Representatives — writes and passes the laws.',
      ex: 'Passing a national budget or a new law about clean water.',
      eli5: 'They’re the rule-writers — the group that makes up the rules of the game.' },
    { term: 'Executive Branch', icon: '🦅', cat: 'branches', img: 'img/whitehouse.webp',
      def: 'The branch of government that carries out and enforces the laws.',
      kid: 'The President leads it, along with the Cabinet and agencies, and makes sure laws are followed.',
      ex: 'The President signs a bill into law or commands the military.',
      eli5: 'The head referee — makes sure everyone actually follows the rules.' },
    { term: 'Judicial Branch', icon: '⚖️', cat: 'branches', img: 'img/supremecourt.webp',
      def: 'The branch of government that interprets the laws and settles disputes.',
      kid: 'The courts — topped by the Supreme Court — decide what laws mean and whether they follow the Constitution.',
      ex: 'The Supreme Court deciding if a law is constitutional.',
      eli5: 'The umpires — when people disagree about a rule, they decide what it really means.' },
    { term: 'Checks and Balances', icon: '⚖️', cat: 'system',
      def: 'The system that lets each branch limit the power of the other two.',
      kid: 'No branch can get too powerful — each one can check the others.',
      ex: 'The President can veto a bill; Congress can override the veto; courts can strike laws down.',
      eli5: 'Like rock-paper-scissors: every branch can beat another, so nobody wins forever.' },
    { term: 'Separation of Powers', icon: '🧩', cat: 'system',
      def: 'Dividing government power among three separate branches.',
      kid: 'Splitting the job of governing so no single group controls everything.',
      ex: 'Law-making, law-enforcing, and law-judging are done by different branches.',
      eli5: 'Don’t let one kid write the rules, enforce the rules, AND judge the rules — split up the jobs.' },
    { term: 'Federalism', icon: '🗺️', cat: 'system',
      def: 'Sharing power between a national government and state governments.',
      kid: 'Some powers belong to the whole country, some to each state, and some are shared.',
      ex: 'The nation runs the military; states run public schools.',
      eli5: 'The school makes school-wide rules, but each classroom still makes its own rules too.' },
    { term: 'Constitution', icon: '📜', cat: 'documents', img: 'img/constitution.webp',
      def: 'The supreme law that sets up the government and its powers.',
      kid: 'The rulebook for the whole U.S. government — the highest law in the land.',
      ex: 'It creates Congress, the presidency, and the courts.',
      eli5: 'The rulebook everyone has to play by — even the President.' },
    { term: 'Bill of Rights', icon: '📃', cat: 'documents', img: 'img/billofrights.webp',
      def: 'The first ten amendments to the Constitution, protecting individual freedoms.',
      kid: 'Ten promises added in 1791 that protect your basic rights from the government.',
      ex: 'Free speech, freedom of religion, and the right to a fair trial.',
      eli5: 'The “you can’t touch this” list — ten things the government can never take from you.' },
    { term: 'Declaration of Independence', icon: '🖋️', cat: 'documents', img: 'img/declaration.webp',
      def: 'The 1776 document that announced the colonies were free from Britain.',
      kid: 'It declared independence and said all people have rights like life, liberty, and the pursuit of happiness.',
      ex: 'Adopted July 4, 1776 — it explained WHY the colonies broke away.',
      eli5: 'America’s breakup letter to Britain: “We’re done — and here’s why.”' },
    { term: 'Amendment', icon: '✏️', cat: 'documents',
      def: 'An official change or addition to the Constitution.',
      kid: 'A way to update the Constitution — there have been 27 so far.',
      ex: 'The 19th Amendment gave women the right to vote.',
      eli5: 'A pencil-and-eraser for the Constitution — the official way to update the rulebook.' },
    { term: 'Democracy', icon: '🗳️', cat: 'systems',
      def: 'A form of government in which the people hold the power.',
      kid: 'Rule by the people — citizens make decisions, often by voting.',
      ex: 'Citizens vote to choose their leaders and shape the laws.',
      eli5: 'Everyone gets a say — the people are the boss.' },
    { term: 'Republic', icon: '🏛️', cat: 'systems',
      def: 'A government where people elect representatives to make decisions for them.',
      kid: 'You don’t vote on every law — you vote for leaders who do it for you.',
      ex: 'Americans elect members of Congress to write laws.',
      eli5: 'You pick a classmate to speak for the whole class instead of everyone shouting at once.' },
    { term: 'Monarchy', icon: '👑', cat: 'systems',
      def: 'A government led by a king or queen, often inheriting the throne.',
      kid: 'One royal ruler is in charge, usually passed down through a family.',
      ex: 'Saudi Arabia is ruled by a king with real power.',
      eli5: 'One family wears the crown, and “ruler” gets passed down like a family heirloom.' },
    { term: 'Popular Sovereignty', icon: '🙋', cat: 'system',
      def: 'The idea that government gets its power from the consent of the people.',
      kid: 'The government only has power because the people give it power.',
      ex: 'The Constitution begins “We the People…”.',
      eli5: 'The government works for you — the people are the boss, not the other way around.' },
    { term: 'Veto', icon: '🚫', cat: 'system',
      def: 'The President’s power to reject a bill passed by Congress.',
      kid: 'The President can say “no” to a bill and send it back.',
      ex: 'Congress can override a veto with a two-thirds vote.',
      eli5: 'The President’s big red NO stamp.' },
    { term: 'Bill', icon: '📄', cat: 'lawmaking',
      def: 'A proposed law being considered by a legislature.',
      kid: 'An idea for a law before it has been passed and signed.',
      ex: 'A bill must pass both houses of Congress to move forward.',
      eli5: 'A law that’s still just an idea — a rough draft before it gets graded.' },
    { term: 'Political Party', icon: '🎗️', cat: 'participation',
      def: 'An organized group that shares ideas and runs candidates for office.',
      kid: 'A team of people with similar beliefs who try to win elections.',
      ex: 'The Democratic and Republican parties in the U.S.',
      eli5: 'A team of people who agree on stuff and try to win elections together.' },
    { term: 'Jury', icon: '👥', cat: 'participation', img: 'img/jury.webp',
      def: 'A group of citizens who decide the facts of a court case.',
      kid: 'Ordinary people who listen to a trial and reach a verdict.',
      ex: 'A jury of 12 decides whether someone is guilty.',
      eli5: 'Regular people — not just judges — get to decide the case, so it stays fair.' },
    { term: 'Suffrage', icon: '🗳️', cat: 'participation', img: 'img/voting.webp',
      def: 'The right to vote in elections.',
      kid: 'Being allowed to vote — a right expanded many times in U.S. history.',
      ex: 'The 15th, 19th, and 26th Amendments all expanded suffrage.',
      eli5: 'Being allowed to vote. (Nothing to do with suffering — it comes from an old word for “vote.”)' },
    { term: 'Town Meeting', icon: '🏘️', cat: 'ma', img: 'img/townmeeting.webp',
      def: 'A form of local government where residents gather to vote directly on town matters.',
      kid: 'In many Massachusetts towns, citizens meet and vote in person on the budget and local rules.',
      ex: 'Plymouth, MA and many New England towns still use town meeting.',
      eli5: 'The whole town shows up and votes by raising hands — democracy in one room.' },
    { term: 'Ratify', icon: '✅', cat: 'documents',
      def: 'To formally approve something, like the Constitution or an amendment.',
      kid: 'To officially say “yes” and make it count.',
      ex: 'The states ratified the Constitution in 1788.',
      eli5: 'The official “yes, let’s make it real” vote.' },
    { term: 'Rule of Law', icon: '📏', cat: 'system',
      def: 'The idea that everyone, including leaders, must obey the law.',
      kid: 'No one is above the law — not even the President.',
      ex: 'A leader can be taken to court just like anyone else.',
      eli5: 'The rules apply to EVERYONE — even the person who made them.' }
  ],
  TERM_CATS: [
    ['all', 'All'], ['branches', '🏛️ Branches'], ['system', '⚙️ How It Works'],
    ['documents', '📜 Documents'], ['systems', '🗳️ Gov. Types'],
    ['participation', '🙋 Taking Part'], ['lawmaking', '📄 Lawmaking'], ['ma', '🦞 Massachusetts']
  ],

  // =====================================================================
  // GAME 2 — CONSTITUTION QUIZ: multiple-choice, straight from the
  // framework's 20 questions (plus a few extras). Each has a source key.
  // `dia` links the reveal to a diagram in the 📖 Diagrams popup.
  // =====================================================================
  CONSTITUTION: [
    { q: 'What are the three branches of the U.S. government?',
      choices: ['Legislative, Executive, Judicial', 'Federal, State, Local', 'House, Senate, President', 'Army, Navy, Air Force'],
      answer: 0, src: 'usagov', dia: 'checks',
      explain: 'The Legislative branch makes laws, the Executive branch carries them out, and the Judicial branch interprets them.',
      eli5: 'Making rules, enforcing rules, and judging rules — three jobs, three teams.' },
    { q: 'What is the main purpose of the U.S. Constitution?',
      choices: ['To set up the government and protect people’s rights', 'To declare war on Britain', 'To list the 50 states', 'To choose a national anthem'],
      answer: 0, src: 'archives',
      explain: 'The Constitution creates the framework of government and limits its power to protect the people’s rights. It is the supreme law of the land.',
      eli5: 'It’s the instruction manual AND the rulebook for America, all in one.' },
    { q: 'What does the system of "checks and balances" do?',
      choices: ['Lets each branch limit the power of the others', 'Balances the national budget', 'Counts the votes in an election', 'Divides the country into states'],
      answer: 0, src: 'usagov', dia: 'checks',
      explain: 'Each branch can “check” the others so no single branch becomes too powerful — for example, the President can veto a law and courts can strike it down.',
      eli5: 'Rock-paper-scissors: every branch can beat another, so nobody wins forever.' },
    { q: 'Which of these is a right protected by the First Amendment?',
      choices: ['Freedom of speech', 'The right to a driver’s license', 'The right to free healthcare', 'The right to own a car'],
      answer: 0, src: 'bor',
      explain: 'The First Amendment protects five freedoms: religion, speech, press, assembly, and petition.',
      eli5: 'You can say what you think — even about the government — without getting punished for it.' },
    { q: 'How is the Declaration of Independence different from the Constitution?',
      choices: ['It declared freedom from Britain; the Constitution sets up the government', 'They are the same document', 'The Declaration created Congress', 'The Constitution came first'],
      answer: 0, src: 'doi',
      explain: 'The Declaration (1776) announced independence and its reasons. The Constitution (1787) later built the actual government.',
      eli5: 'The Declaration is the breakup letter; the Constitution is the new house rules.' },
    { q: 'What is federalism?',
      choices: ['Sharing power between the national and state governments', 'Rule by a single king', 'A tax on imported goods', 'A type of election'],
      answer: 0, src: 'ma', dia: 'venn',
      explain: 'Under federalism, some powers belong to the national government, some to the states, and some are shared.',
      eli5: 'School-wide rules vs. classroom rules — some things the whole school decides, some things each class decides.' },
    { q: 'What is the Bill of Rights?',
      choices: ['The first ten amendments to the Constitution', 'The list of U.S. presidents', 'A tax law', 'The rules of Congress'],
      answer: 0, src: 'bor',
      explain: 'The Bill of Rights (ratified 1791) is the first ten amendments, protecting freedoms like speech, religion, and a fair trial.',
      eli5: 'The top-10 list of things the government can never take away from you.' },
    { q: 'Which is a RESPONSIBILITY of a citizen (not just a right)?',
      choices: ['Serving on a jury when called', 'Speaking freely', 'Practicing any religion', 'Owning property'],
      answer: 0, src: 'ma',
      explain: 'Rights are freedoms you’re guaranteed; responsibilities are duties you’re expected to fulfill, like serving on a jury, obeying laws, and voting.',
      eli5: 'A right is something you GET; a responsibility is something you’re expected to DO.' },
    { q: 'At the federal level, where does a bill usually START on its way to becoming a law?',
      choices: ['It is introduced in Congress (House or Senate)', 'The President writes it alone', 'The Supreme Court passes it', 'The states vote on it first'],
      answer: 0, src: 'congress', dia: 'bill',
      explain: 'A bill is introduced in Congress, studied in committee, passed by both the House and Senate, and then signed by the President to become law.',
      eli5: 'A law starts as homework in Congress — it gets checked lots of times before it counts.' },
    { q: 'What are the three LEVELS of government in the United States?',
      choices: ['Federal, State, Local', 'Legislative, Executive, Judicial', 'City, County, Town', 'Mayor, Governor, President'],
      answer: 0, src: 'usagov', dia: 'pyramid',
      explain: 'Government works at three levels: federal (national), state, and local (city or town).',
      eli5: 'Country-wide, state-wide, and your-own-town — like principal, teacher, and group leader.' },
    { q: 'What is the main role of the Supreme Court?',
      choices: ['To interpret the Constitution and decide if laws are constitutional', 'To write new laws', 'To command the army', 'To collect taxes'],
      answer: 0, src: 'court',
      explain: 'The Supreme Court is the highest court. It interprets the Constitution and can declare laws or actions unconstitutional.',
      eli5: 'The final umpire — their call on what the rules mean is the last word.' },
    { q: 'Besides voting, name one way a citizen can take part in democracy.',
      choices: ['Attending a town meeting or contacting an official', 'Ignoring the news', 'Paying no taxes', 'Refusing jury duty'],
      answer: 0, src: 'icivics',
      explain: 'Citizens can volunteer, join groups, contact officials, protest peacefully, serve on juries, or attend meetings — not just vote.',
      eli5: 'Democracy isn’t just voting day — you can speak up, help out, and show up all year long.' },
    { q: 'What is the main difference between a democracy and a monarchy?',
      choices: ['In a democracy the people hold power; in a monarchy a king or queen does', 'They are the same', 'A democracy has no laws', 'A monarchy has no leader'],
      answer: 0, src: 'ma',
      explain: 'In a democracy, power comes from the people. In a monarchy, a king or queen rules — sometimes with total power, sometimes only as a symbol.',
      eli5: 'Everyone’s the boss vs. one crowned boss.' },
    { q: 'The U.S. is a "representative democracy," or republic. What does that mean?',
      choices: ['People elect representatives to make laws for them', 'Everyone votes on every single law', 'A king makes the laws', 'Only judges make decisions'],
      answer: 0, src: 'ma',
      explain: 'Instead of voting on every law directly, citizens elect representatives (like members of Congress) to make decisions for them.',
      eli5: 'You pick someone to speak for you instead of everyone voting on every single thing.' },
    { q: 'Who heads the executive branch at the FEDERAL level?',
      choices: ['The President', 'The Speaker of the House', 'The Chief Justice', 'A governor'],
      answer: 0, src: 'usagov', dia: 'pyramid',
      explain: 'The President heads the federal executive branch. At the STATE level, a governor heads the executive branch.',
      eli5: 'The President runs the country’s to-do list; a governor runs the state’s.' },
    { q: 'What is the purpose of political parties?',
      choices: ['To organize people with similar ideas and run candidates', 'To count votes officially', 'To act as judges', 'To collect taxes'],
      answer: 0, src: 'icivics',
      explain: 'Political parties group people with shared ideas, choose candidates, and help voters understand what candidates stand for.',
      eli5: 'Teams for elections — people who agree on stuff working together to win.' },
    { q: 'What does "popular sovereignty" mean?',
      choices: ['Government’s power comes from the people', 'The most popular person becomes king', 'The majority is always right', 'Only landowners can vote'],
      answer: 0, src: 'ma',
      explain: 'Popular sovereignty means government gets its authority from the consent of the people — “We the People.”',
      eli5: 'The people are the boss. The government works for us, not the other way around.' },
    { q: 'Why does serving on a jury matter?',
      choices: ['Ordinary citizens help decide court cases fairly', 'Juries write new laws', 'Juries elect the President', 'Juries set tax rates'],
      answer: 0, src: 'court',
      explain: 'A jury of everyday citizens decides the facts of a case, which keeps the justice system fair and in the hands of the people.',
      eli5: 'Regular people make sure trials stay fair — not just the people in charge.' },
    { q: 'In Massachusetts, what is a "town meeting"?',
      choices: ['Residents gather and vote directly on local matters', 'A meeting of the governor and mayors', 'A statewide election', 'A session of Congress'],
      answer: 0, src: 'mass',
      explain: 'Many Massachusetts towns, like Plymouth, use town meeting — a form of direct democracy where residents vote in person on the budget and local rules.',
      eli5: 'The whole town raises hands to vote — democracy in one big room.' },
    { q: 'Why is the right to vote considered so important in a democracy?',
      choices: ['It lets people choose their leaders and shape the laws', 'It is required to get a job', 'It lowers taxes automatically', 'It is only for the wealthy'],
      answer: 0, src: 'icivics',
      explain: 'Voting is how the people give their consent and hold leaders accountable — it’s the heart of self-government.',
      eli5: 'Voting is how you hire — and fire — your leaders.' },
    { q: 'How can the Constitution be changed?',
      choices: ['By adding an amendment', 'By a presidential order', 'By a Supreme Court vote alone', 'It can never be changed'],
      answer: 0, src: 'archives',
      explain: 'The Constitution is changed by amendment — a difficult process needing large majorities in Congress and approval by the states. There are 27 amendments.',
      eli5: 'Changing the rulebook takes almost everyone agreeing — and that’s on purpose.' },
    { q: 'The Massachusetts Constitution (1780) is special because…',
      choices: ['It is the oldest written constitution still in use in the world', 'It was written by the President', 'It created the U.S. Congress', 'It has no amendments'],
      answer: 0, src: 'mass',
      explain: 'Written mostly by John Adams in 1780, the Massachusetts Constitution is the oldest functioning written constitution in the world and helped inspire the U.S. Constitution.',
      eli5: 'Massachusetts wrote the beta version — and it still runs today.' }
  ],

  // =====================================================================
  // GAME 3 — WORLD GOVERNMENTS: match a country to its type of government.
  // Types are simplified for grade 8 but based on the CIA World Factbook.
  // =====================================================================
  GOVTYPES: {
    'Federal Republic':        { icon: '🏛️', desc: 'People elect representatives, and power is shared between a national government and states or regions.',
                                 eli5: 'You elect people to run things, and power is split between the whole country and its states.' },
    'Constitutional Monarchy': { icon: '👑', desc: 'A king or queen is head of state, but elected leaders and a constitution actually run the government.',
                                 eli5: 'There’s a king or queen, but they’re mostly for show — elected leaders do the real work.' },
    'Parliamentary Democracy': { icon: '🗳️', desc: 'Voters elect a parliament, which chooses a prime minister to lead the government.',
                                 eli5: 'You vote for the class, and then the class picks the class president.' },
    'Absolute Monarchy':       { icon: '👑', desc: 'A king or royal family holds nearly all the power, with few limits.',
                                 eli5: 'The king’s word IS the law.' },
    'One-Party State':         { icon: '⭐', desc: 'A single political party controls the government, and no real opposition is allowed.',
                                 eli5: 'Only one team is allowed to play — and it always wins.' },
    'Direct Democracy':        { icon: '🙋', desc: 'Citizens vote directly on many laws themselves, not just for representatives.',
                                 eli5: 'No middlemen — the people vote on the rules themselves.' },
    'Theocratic Republic':     { icon: '🕌', desc: 'Elected officials share power with religious leaders, and religious law shapes the government.',
                                 eli5: 'Religious leaders get the final say — even over the elected ones.' }
  },
  GOV_COUNTRIES: [
    { name: 'United States', flag: '🇺🇸', type: 'Federal Republic', head: 'President',
      fact: 'A federal republic of 50 states. Citizens elect a President and members of Congress; power is split by federalism and checks and balances.' },
    { name: 'United Kingdom', flag: '🇬🇧', type: 'Constitutional Monarchy', head: 'Monarch + Prime Minister',
      fact: 'A king or queen is the head of state, but an elected Parliament and a Prime Minister actually govern. The UK has no single written constitution.' },
    { name: 'Japan', flag: '🇯🇵', type: 'Constitutional Monarchy', head: 'Emperor + Prime Minister',
      fact: 'The Emperor is a symbol of the nation with no political power; the elected Diet (parliament) and Prime Minister run the government.' },
    { name: 'Saudi Arabia', flag: '🇸🇦', type: 'Absolute Monarchy', head: 'King',
      fact: 'A king from the Al Saud family holds almost all power. There is no elected national legislature and no constitution like the U.S. one.' },
    { name: 'China', flag: '🇨🇳', type: 'One-Party State', head: 'President (Party leader)',
      fact: 'The Chinese Communist Party controls the government. Opposition parties are not allowed to compete for power.' },
    { name: 'Germany', flag: '🇩🇪', type: 'Federal Republic', head: 'Chancellor',
      fact: 'A federal republic where voters elect a parliament (the Bundestag), which chooses a Chancellor. Power is shared with 16 states.' },
    { name: 'India', flag: '🇮🇳', type: 'Federal Republic', head: 'Prime Minister',
      fact: 'The world’s most populous democracy — a federal republic with a parliament and states, guided by a written constitution from 1950.' },
    { name: 'Sweden', flag: '🇸🇪', type: 'Constitutional Monarchy', head: 'Monarch + Prime Minister',
      fact: 'A king serves as a ceremonial head of state, while an elected parliament (Riksdag) and Prime Minister make the decisions.' },
    { name: 'Switzerland', flag: '🇨🇭', type: 'Direct Democracy', head: 'Federal Council',
      fact: 'Famous for direct democracy: citizens often vote directly on laws and changes through frequent referendums.' },
    { name: 'Iran', flag: '🇮🇷', type: 'Theocratic Republic', head: 'Supreme Leader + President',
      fact: 'Voters elect a president and parliament, but a religious Supreme Leader and clerics hold the highest power under Islamic law.' },
    { name: 'North Korea', flag: '🇰🇵', type: 'One-Party State', head: 'Supreme Leader',
      fact: 'One family and one party have ruled since 1948. Elections offer no real choice, and citizens have very few freedoms.' },
    { name: 'Canada', flag: '🇨🇦', type: 'Constitutional Monarchy', head: 'Monarch + Prime Minister',
      fact: 'A parliamentary democracy AND a constitutional monarchy: the British monarch is head of state, but an elected Prime Minister governs.' },
    { name: 'France', flag: '🇫🇷', type: 'Federal Republic', head: 'President',
      fact: 'A republic where citizens directly elect a President and a National Assembly. (Unlike the U.S., it is not federal — power is more central.)' },
    { name: 'Brazil', flag: '🇧🇷', type: 'Federal Republic', head: 'President',
      fact: 'A federal republic of 26 states, where citizens elect a President and Congress. Voting is required by law for most adults.' },
    { name: 'Spain', flag: '🇪🇸', type: 'Constitutional Monarchy', head: 'Monarch + Prime Minister',
      fact: 'A king is head of state, but an elected parliament (Cortes) and a Prime Minister run the country under a 1978 constitution.' },
    { name: 'Australia', flag: '🇦🇺', type: 'Constitutional Monarchy', head: 'Monarch + Prime Minister',
      fact: 'A parliamentary democracy and constitutional monarchy where voting is compulsory — citizens can be fined for not voting.' }
  ],

  // =====================================================================
  // GAME 4 — YOUR RIGHTS: a right protected in the U.S., which amendment
  // protects it, and how the SAME right looks in other countries.
  // =====================================================================
  RIGHTS: [
    { right: 'Freedom of Speech', icon: '🗣️', amendment: '1st Amendment',
      us: 'You can speak, write, and share opinions — even criticize the government — without being punished by the government.',
      eli5: 'You can say the government is doing a bad job — out loud — and not get arrested for it.',
      world: [
        { country: 'Norway', flag: '🇳🇴', status: 'strong', note: 'Among the freest in the world for speech and press.' },
        { country: 'China', flag: '🇨🇳', status: 'restricted', note: 'The government censors the internet and punishes public criticism.' },
        { country: 'North Korea', flag: '🇰🇵', status: 'restricted', note: 'Almost no free speech; criticizing leaders can bring harsh punishment.' }
      ] },
    { right: 'Freedom of Religion', icon: '🕊️', amendment: '1st Amendment',
      us: 'You can follow any religion, or none at all, and the government cannot set up an official national religion.',
      eli5: 'You pick your own beliefs — the government doesn’t pick them for you.',
      world: [
        { country: 'Canada', flag: '🇨🇦', status: 'strong', note: 'Religious freedom is protected by its Charter of Rights.' },
        { country: 'Saudi Arabia', flag: '🇸🇦', status: 'restricted', note: 'Public worship of other religions is heavily restricted.' },
        { country: 'Iran', flag: '🇮🇷', status: 'restricted', note: 'Religious law shapes the state and limits some faiths.' }
      ] },
    { right: 'Freedom of the Press', icon: '📰', amendment: '1st Amendment',
      us: 'Newspapers, TV, and websites can report the news and criticize leaders without government control.',
      eli5: 'Reporters can tell the truth even when leaders don’t like it.',
      world: [
        { country: 'Sweden', flag: '🇸🇪', status: 'strong', note: 'One of the first nations to protect press freedom, back in 1766.' },
        { country: 'Germany', flag: '🇩🇪', status: 'strong', note: 'A free and independent press is protected by law.' },
        { country: 'North Korea', flag: '🇰🇵', status: 'restricted', note: 'All news is controlled by the state.' }
      ] },
    { right: 'Right to Peaceful Assembly', icon: '🪧', amendment: '1st Amendment',
      us: 'You can gather and protest peacefully, and ask the government to fix problems (petition).',
      eli5: 'You and your friends can gather with signs to say something’s unfair.',
      world: [
        { country: 'France', flag: '🇫🇷', status: 'strong', note: 'Public protest is a well-known part of French political life.' },
        { country: 'China', flag: '🇨🇳', status: 'restricted', note: 'Large unapproved protests are usually broken up.' },
        { country: 'United States', flag: '🇺🇸', status: 'strong', note: 'Protected by the First Amendment.' }
      ] },
    { right: 'Right to Vote', icon: '🗳️', amendment: '15th, 19th & 26th Amendments', img: 'img/voting.webp',
      us: 'Citizens 18 and older can vote. Voting cannot be denied because of race (15th), sex (19th), or age over 18 (26th).',
      eli5: 'Every adult citizen gets a say — no matter their race, sex, or wealth.',
      world: [
        { country: 'Australia', flag: '🇦🇺', status: 'compulsory', note: 'Voting is required by law — you can be fined for not voting.' },
        { country: 'Brazil', flag: '🇧🇷', status: 'compulsory', note: 'Voting is mandatory for most adults.' },
        { country: 'Saudi Arabia', flag: '🇸🇦', status: 'restricted', note: 'There are no national elections for the government.' }
      ] },
    { right: 'Right to a Fair Trial by Jury', icon: '⚖️', amendment: '6th & 7th Amendments', img: 'img/jury.webp',
      us: 'If accused of a crime, you get a speedy, public trial by an impartial jury of citizens, with a lawyer to defend you.',
      eli5: 'If you’re accused, regular people hear your side before anyone can punish you.',
      world: [
        { country: 'United Kingdom', flag: '🇬🇧', status: 'strong', note: 'Jury trials began here centuries ago and are still used for serious crimes.' },
        { country: 'Japan', flag: '🇯🇵', status: 'mixed', note: 'Uses a mix of citizen judges and professional judges (the saiban-in system).' },
        { country: 'China', flag: '🇨🇳', status: 'restricted', note: 'No independent jury system; courts are controlled by the party.' }
      ] },
    { right: 'Protection from Unreasonable Searches', icon: '🔒', amendment: '4th Amendment',
      us: 'Police generally need a warrant from a judge to search your home or belongings.',
      eli5: 'Police can’t dig through your stuff without a judge’s permission slip.',
      world: [
        { country: 'Germany', flag: '🇩🇪', status: 'strong', note: 'Privacy of the home is strongly protected by its Basic Law.' },
        { country: 'China', flag: '🇨🇳', status: 'restricted', note: 'The government runs wide surveillance with few privacy limits.' },
        { country: 'United States', flag: '🇺🇸', status: 'strong', note: 'Protected by the Fourth Amendment.' }
      ] },
    { right: 'Right to Remain Silent (Due Process)', icon: '🤐', amendment: '5th Amendment',
      us: 'You don’t have to testify against yourself, and the government must follow fair legal steps before punishing you.',
      eli5: 'You never have to be a witness against yourself.',
      world: [
        { country: 'Canada', flag: '🇨🇦', status: 'strong', note: 'The Charter protects the right to silence and fair process.' },
        { country: 'India', flag: '🇮🇳', status: 'strong', note: 'The constitution protects against self-incrimination.' },
        { country: 'North Korea', flag: '🇰🇵', status: 'restricted', note: 'Fair legal process is largely absent.' }
      ] },
    { right: 'No Cruel or Unusual Punishment', icon: '🚫', amendment: '8th Amendment',
      us: 'Punishments cannot be cruel or unusual, and bail or fines cannot be excessive.',
      eli5: 'Punishments have to fit the crime — no torture, ever.',
      world: [
        { country: 'Norway', flag: '🇳🇴', status: 'strong', note: 'Prisons focus on rehabilitation; there is no death penalty.' },
        { country: 'Germany', flag: '🇩🇪', status: 'strong', note: 'Human dignity is the first line of its constitution.' },
        { country: 'Saudi Arabia', flag: '🇸🇦', status: 'restricted', note: 'Uses corporal and capital punishments under its legal code.' }
      ] }
  ],

  // =====================================================================
  // GAME 5 — BRANCH SORTER: which branch has this power?
  // =====================================================================
  POWERS: [
    // Legislative
    { icon: '📜', branch: 'legislative', text: 'Makes the nation’s laws',
      why: 'Congress — the House and Senate — writes, debates, and passes federal laws.' },
    { icon: '⚔️', branch: 'legislative', text: 'Declares war',
      why: 'Only Congress can officially declare war, even though the President commands the military.' },
    { icon: '💰', branch: 'legislative', text: 'Controls government spending',
      why: 'Congress holds the “power of the purse” — no federal money can be spent unless Congress approves it.' },
    { icon: '🔁', branch: 'legislative', text: 'Can override a President’s veto',
      why: 'If two-thirds of both houses agree, a bill becomes law even after the President says no.' },
    { icon: '✅', branch: 'legislative', text: 'Confirms Supreme Court justices',
      why: 'The President nominates justices, but the Senate votes to confirm or reject them.' },
    { icon: '🧑‍⚖️', branch: 'legislative', text: 'Can impeach the President',
      why: 'The House can impeach (formally accuse) a President, and the Senate holds the trial.' },
    { icon: '🤝', branch: 'legislative', text: 'Approves treaties with other countries',
      why: 'The President negotiates treaties, but the Senate must approve them by a two-thirds vote.' },
    // Executive
    { icon: '🖋️', branch: 'executive', text: 'Signs bills into law',
      why: 'A bill passed by Congress only becomes law when the President signs it.' },
    { icon: '🚫', branch: 'executive', text: 'Vetoes bills',
      why: 'The President can reject a bill Congress passed and send it back.' },
    { icon: '🎖️', branch: 'executive', text: 'Commands the military',
      why: 'The President is commander-in-chief of the armed forces.' },
    { icon: '🌐', branch: 'executive', text: 'Negotiates treaties',
      why: 'The President and diplomats work out agreements with other countries (which the Senate must then approve).' },
    { icon: '⚖️', branch: 'executive', text: 'Nominates Supreme Court justices',
      why: 'When a seat opens, the President picks the nominee — then the Senate confirms or rejects.' },
    { icon: '👮', branch: 'executive', text: 'Enforces the laws',
      why: 'The executive branch — its agencies, departments, and officers — carries out the laws Congress passes.' },
    { icon: '🕊️', branch: 'executive', text: 'Grants pardons',
      why: 'The President can forgive federal crimes and reduce punishments.' },
    // Judicial
    { icon: '🔍', branch: 'judicial', text: 'Interprets what laws mean',
      why: 'Courts decide how laws apply when people disagree about them.' },
    { icon: '🛑', branch: 'judicial', text: 'Can declare a law unconstitutional',
      why: 'This is judicial review — courts can strike down laws that break the Constitution (established in Marbury v. Madison, 1803).' },
    { icon: '🗺️', branch: 'judicial', text: 'Settles disputes between states',
      why: 'When states disagree — say, over a border or a river — the Supreme Court decides.' },
    { icon: '📤', branch: 'judicial', text: 'Hears appeals from lower courts',
      why: 'Higher courts review lower-court decisions to correct mistakes.' },
    { icon: '✋', branch: 'judicial', text: 'Can rule the President’s actions unconstitutional',
      why: 'Even the President must follow the Constitution — courts can block actions that don’t.' },
    { icon: '🏛️', branch: 'judicial', text: 'Decides cases about federal law',
      why: 'Federal courts hear cases involving the Constitution, federal laws, and treaties.' },
    { icon: '👩‍⚖️', branch: 'judicial', text: 'Presides over a President’s impeachment trial',
      why: 'When a President is tried in the Senate, the Chief Justice of the Supreme Court runs the trial.' }
  ],

  // =====================================================================
  // GAME 6 — ORDER IT!: put the steps in the correct order.
  // =====================================================================
  SEQUENCES: [
    { title: 'How a bill becomes a law', icon: '📄', src: 'congress', dia: 'bill',
      note: 'Fun fact: a bill can actually start in either the House or the Senate (except tax bills, which must start in the House). Both must pass the exact same version.',
      steps: [
        { icon: '💡', text: 'Someone has an idea for a new law', desc: 'Ideas can come from anyone — citizens, groups, or lawmakers.' },
        { icon: '📄', text: 'A member of Congress introduces the bill', desc: 'Only a member of the House or Senate can introduce a bill.' },
        { icon: '🔍', text: 'A committee studies, changes, and votes on the bill', desc: 'Most bills “die” in committee — only the strong survive.' },
        { icon: '🏛️', text: 'The House debates and votes to pass it', desc: 'A majority — more than half — must vote yes.' },
        { icon: '🏛️', text: 'The Senate debates and passes the same version', desc: 'Both chambers must agree on identical text.' },
        { icon: '🖋️', text: 'The President signs the bill — or vetoes it', desc: 'A veto sends it back; Congress can override with a two-thirds vote.' },
        { icon: '⚖️', text: 'It becomes a law of the United States', desc: 'Now the executive branch enforces it and the courts interpret it.' }
      ] },
    { title: 'The founding of American government', icon: '🇺🇸', src: 'archives',
      note: 'Eleven years passed between declaring independence (1776) and writing the Constitution (1787).',
      steps: [
        { icon: '⚔️', text: '1775 — The Revolutionary War begins', desc: 'Fighting breaks out at Lexington and Concord, Massachusetts.' },
        { icon: '🖋️', text: '1776 — The Declaration of Independence', desc: 'The colonies declare they are free from Britain.' },
        { icon: '🕊️', text: '1783 — The war ends', desc: 'Britain recognizes American independence in the Treaty of Paris.' },
        { icon: '🏛️', text: '1787 — The Constitutional Convention', desc: 'Delegates in Philadelphia write the U.S. Constitution.' },
        { icon: '✅', text: '1788 — The states ratify the Constitution', desc: 'New Hampshire is the 9th state to say yes, making it official.' },
        { icon: '📃', text: '1791 — The Bill of Rights is added', desc: 'The first ten amendments protect individual freedoms.' }
      ] },
    { title: 'How the Constitution gets amended', icon: '✏️', src: 'archives',
      note: 'It’s hard on purpose — only 27 amendments have made it in over 230 years.',
      steps: [
        { icon: '✏️', text: 'Someone proposes a change to the Constitution', desc: 'Most amendments start in Congress.' },
        { icon: '🏛️', text: 'Two-thirds of both houses of Congress approve it', desc: 'A very high bar — both the House and the Senate.' },
        { icon: '🗺️', text: 'The proposal is sent to all the states', desc: 'Each state legislature (or convention) votes on it.' },
        { icon: '✅', text: 'Three-fourths of the states ratify it', desc: 'Today that means 38 of the 50 states.' },
        { icon: '📜', text: 'It becomes part of the Constitution', desc: 'It now carries the same force as the original document.' }
      ] }
  ]
};
