// One-time addendum: base experience and growth rate for all 151 Pokémon.
//
// dex.js came from the Learn Zone and carries stats, types and catch rates but
// not these two. They're what make levelling realistic:
//   • baseExp  — how much XP defeating this Pokémon is worth. A Magikarp should
//                be worth far less than a Dragonite; a flat number can't do that.
//   • growth   — the XP curve (fast / medium / slow / medium-slow). Starters and
//                legendaries level slowly on purpose.
// Writes data/growth.js. Run once; the output is committed.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const API = 'https://pokeapi.co/api/v2';

const get = async (url) => {
  for (let tries = 0; tries < 4; tries++) {
    try {
      const r = await fetch(url);
      if (r.ok) return r.json();
    } catch { /* retry */ }
    await new Promise(r => setTimeout(r, 400 * (tries + 1)));
  }
  throw new Error('failed: ' + url);
};

const out = {};
for (let id = 1; id <= 151; id++) {
  const [mon, sp] = await Promise.all([get(`${API}/pokemon/${id}`), get(`${API}/pokemon-species/${id}`)]);
  out[id] = { exp: mon.base_experience ?? 64, growth: sp.growth_rate?.name ?? 'medium' };
  if (id % 25 === 0) process.stdout.write(`  ${id}/151\n`);
}

writeFileSync(join(ROOT, 'data/growth.js'),
`// GENERATED by tools/fetch-growth.mjs — DO NOT EDIT BY HAND.
// { dexId: { exp: base experience yield, growth: XP curve name } }
window.PL_GROWTH = ${JSON.stringify(out)};
`);
console.log('Wrote data/growth.js — 151 species.');
