// Grease Monkey Garage — car & mechanic learning content.
// Parts drawn by carart.js. Facts kept accurate and kid-friendly, and written
// to actually TEACH: what a part does, how it works, where it lives, and a
// "did you know" to make it stick.
window.CARS = {

  // ---- GAME 1: NAME THAT PART (icon shown → pick the name; reveal teaches) ----
  // `key` matches a CARART.part() icon. `cat` drives the category filter.
  PARTS: [
    { key:'engine', name:'Engine', cat:'engine',
      job:'The engine is where the car makes its power. It mixes fuel with air and sets off thousands of tiny, controlled explosions every minute. Each little explosion shoves a piece of metal called a piston down, and those pistons spin a shaft that ends up turning the wheels. People call it the car’s “heart” because everything else works to keep it running.',
      where:'Under the hood at the front of most cars. (A few sports cars and buses hide it in the back.)',
      fact:'At highway speed a normal engine fires its spark plugs more than 1,000 times every second — that’s why it hums so smoothly instead of going “bang… bang… bang.”' },
    { key:'battery', name:'Battery', cat:'electric',
      job:'The battery stores electricity like a big rechargeable power pack. Its biggest job is the huge jolt of power needed to crank the engine to life when you turn the key. It also runs the lights, radio, and computers when the engine is off — and the alternator refills it while you drive.',
      where:'Under the hood, usually bolted into one front corner. Some cars tuck it in the trunk instead.',
      fact:'A car battery is only 12 volts — about the same as eight AA batteries — but for one second it can shove out hundreds of amps, enough to spin a cold engine to life.' },
    { key:'tire', name:'Tire', cat:'wheels',
      job:'Tires are the only part of the car that actually touches the road — each one grips through a patch of rubber about the size of your hand. That grip is what lets the car speed up, turn corners, and stop. They’re filled with air, which also cushions bumps so the ride feels smooth.',
      where:'One at each corner of the car. Most cars also carry a spare in the trunk.',
      fact:'The grippy grooves are called “tread.” When they wear down flat, the tire can’t push rain out of the way and the car starts to slide — that’s why worn tires get replaced.' },
    { key:'brakes', name:'Brakes', cat:'wheels',
      job:'Brakes turn motion into heat to slow you down. When you press the brake pedal, a clamp called a caliper squeezes two brake pads against a spinning metal disc at each wheel. The rubbing (friction) scrubs off speed and makes a lot of heat. The harder you press, the harder they squeeze.',
      where:'Behind each wheel, hidden inside the rim.',
      fact:'Hard braking can heat the discs past 500°F — hot enough to glow. Watch a race car stop and you can sometimes see the brakes glowing orange!' },
    { key:'sparkplug', name:'Spark Plug', cat:'engine',
      job:'A spark plug is like a tiny lighter for the engine. At exactly the right instant, it snaps a small electric spark that lights the fuel-and-air mixture inside a cylinder. That mini explosion is what pushes the piston down and makes power. Every cylinder gets its own spark plug.',
      where:'Screwed into the top of the engine — one per cylinder, so a 4-cylinder engine has four.',
      fact:'The spark jumps a gap thinner than a coin, yet it has to fire in perfect time, thousands of times a minute, without ever missing a beat.' },
    { key:'radiator', name:'Radiator', cat:'engine',
      job:'The radiator keeps the engine from cooking itself. Hot liquid coolant flows out of the engine into the radiator’s many thin tubes, and air rushing through the fins cools it down before it circles back to soak up more heat. Without it, an engine would overheat in just a few minutes.',
      where:'Right at the very front, behind the grille, where it catches the most airflow.',
      fact:'Those grille holes in the front of a car aren’t just for looks — they’re there to feed cool outside air straight to the radiator.' },
    { key:'oil', name:'Oil', cat:'engine',
      job:'Oil is the engine’s slippery lifeblood. It coats all the fast-moving metal parts so they glide past each other instead of grinding, and it also carries away heat and tiny bits of dirt. Running low on oil, or letting it get old and dirty, is one of the fastest ways to wreck an engine.',
      where:'It pools in the bottom of the engine. You check the level with a metal stick called a dipstick.',
      fact:'Mechanics say an oil change is “the cheapest way to save an engine,” because fresh oil does its job for a few dollars while a ruined engine costs thousands.' },
    { key:'alternator', name:'Alternator', cat:'electric',
      job:'The alternator is a small generator that the engine spins with a rubber belt. While you drive, it makes fresh electricity — enough to refill the battery AND power the lights, wipers, and everything electrical at the same time. Without it, the battery would slowly drain and the car would die.',
      where:'Bolted to the side of the engine, spun by a belt that loops around several pulleys.',
      fact:'This is the reason a car can run for hours without the battery going flat: the alternator is quietly recharging it the whole time you’re moving.' },
    { key:'steering', name:'Steering Wheel', cat:'controls',
      job:'The steering wheel is how the driver aims the car. Turning it moves the two front wheels left or right through a set of gears and rods. Most cars add “power steering,” which uses the engine’s help to push the wheels, so it turns with just a light touch.',
      where:'Right in front of the driver, on the dashboard.',
      fact:'Old cars had no power steering, so turning the wheel — especially while parking — was a real arm workout!' },
    { key:'seatbelt', name:'Seat Belt', cat:'safety',
      job:'A seat belt holds you firmly in your seat so you aren’t thrown around or flung forward in a sudden stop or a crash. It’s built to spread the force across the strongest parts of your body — your hips and shoulders — instead of letting you hit the dashboard.',
      where:'At every single seat in the car.',
      fact:'The seat belt is the most effective safety feature ever put in a car. It saves tens of thousands of lives every year — which is why buckling up is the law.' },
    { key:'headlight', name:'Headlight', cat:'safety',
      job:'Headlights light up the road ahead so you can drive safely in the dark, fog, or rain — and just as importantly, they let other drivers see YOU. Most have a “low beam” for normal driving and a brighter “high beam” for empty roads with no cars coming.',
      where:'On the two front corners of the car.',
      fact:'The red lights on the back are “tail lights,” and the extra-bright red ones that snap on when you press the brake are “brake lights” — they warn the driver behind you that you’re slowing down.' },
    { key:'transmission', name:'Transmission', cat:'engine',
      job:'The transmission is a box of gears that decides how much of the engine’s power reaches the wheels. Low gears give lots of force to get moving from a stop; high gears let the engine relax while you cruise fast. An “automatic” picks the gears for you, while a “manual” lets the driver shift them by hand.',
      where:'Bolted directly to the back of the engine.',
      fact:'It works just like the gears on a bicycle — an easy gear to grind up a hill, and a hard gear to zoom along on the flat.' },
    { key:'exhaust', name:'Exhaust / Muffler', cat:'engine',
      job:'After the engine burns fuel, it’s left with hot, smelly waste gases. The exhaust system pipes those gases safely out the back of the car, quiets the loud engine noise with the muffler, and even cleans up much of the pollution using a part called the catalytic converter.',
      where:'Underneath the car, running from the engine all the way to a pipe at the back bumper.',
      fact:'That fat silver oval under the middle of the car is the muffler. Without it, an engine would be as loud as a race car or a motorcycle with no pipe.' },
    { key:'airfilter', name:'Air Filter', cat:'engine',
      job:'The air filter cleans the air before it goes into the engine, trapping dust, dirt, pollen, and bugs. An engine needs to breathe in a huge amount of air to burn its fuel, so that air has to be clean. A clogged, dirty filter chokes the engine, saps its power, and wastes gas.',
      where:'Inside a plastic box on top of or beside the engine — it clips open so it’s easy to check.',
      fact:'For every single gallon of gas it burns, an engine breathes in thousands of gallons of air. That’s a lot of air to keep clean!' },
    { key:'wiper', name:'Windshield Wiper', cat:'controls',
      job:'Windshield wipers sweep rain, snow, and grime off the glass so the driver can see clearly. A soft rubber blade drags across the windshield, and a spray of washer fluid helps scrub away bugs and road dirt that plain water can’t.',
      where:'Resting at the bottom edge of the windshield.',
      fact:'The windshield wiper was invented by Mary Anderson in 1903, after she watched a streetcar driver struggle to see through the snow and thought, “there has to be a better way.”' },
    { key:'fuelpump', name:'Fuel Pump', cat:'engine',
      job:'The fuel pump pushes gasoline from the tank up to the engine. Because the tank sits at the back of the car and the engine is up front, the fuel needs a pump to keep it flowing steadily through a long line so the engine never runs dry.',
      where:'Usually sitting right inside the fuel tank, surrounded by the gas.',
      fact:'Electric cars don’t have a fuel pump at all — with no gasoline to move, they run purely on electricity stored in a big battery pack.' }
  ],
  PART_CATS: [
    ['all','All'], ['engine','⚙️ Engine'], ['wheels','🛞 Wheels & Brakes'],
    ['electric','🔋 Electrical'], ['safety','🦺 Safety'], ['controls','🎮 Controls']
  ],

  // ---- GAME 2: UNDER THE HOOD (tap the part on the car diagram) ----
  // `hint` is the short clue shown before tapping; `learn` teaches in the reveal.
  DIAGRAM_PARTS: [
    { key:'engine', name:'Engine', hint:'The “heart” that makes the power.',
      learn:'The engine lives up front under the hood. It burns fuel to create the power that turns the wheels, so almost everything else in the car is there to help the engine run and send that power to the road.' },
    { key:'battery', name:'Battery', hint:'It stores the electricity that starts the car.',
      learn:'The battery is tucked into a front corner under the hood. It delivers the big jolt of electricity that cranks the engine to life, and it runs the lights and electronics when the engine is off.' },
    { key:'radiator', name:'Radiator', hint:'It keeps the engine from overheating.',
      learn:'The radiator sits at the very front behind the grille so it catches the most air. Coolant carries heat away from the engine and dumps it out through the radiator’s fins, keeping the engine from cooking itself.' },
    { key:'headlight', name:'Headlight', hint:'It lights up the road at night.',
      learn:'Headlights are on the front corners of the car. They light the road ahead in the dark and help other drivers see you coming — the red lights at the back do the opposite job.' },
    { key:'brakes', name:'Brakes', hint:'They slow and stop the wheels.',
      learn:'The brakes hide behind each wheel, inside the rim. Pads squeeze a spinning disc to slow the car down — this front wheel is a great spot to see where they live.' },
    { key:'fueltank', name:'Fuel Tank', hint:'It holds the gasoline.',
      learn:'The fuel tank sits low and toward the back, safely away from the hot engine. It stores the gasoline, and the fuel pump inside it sends the fuel forward to the engine.' },
    { key:'exhaust', name:'Exhaust Pipe', hint:'It sends waste gases out the back.',
      learn:'The exhaust runs along the underside of the car from the engine to the back bumper. It carries away the engine’s hot waste gases and, thanks to the muffler, keeps the car quiet.' },
    { key:'steering', name:'Steering Wheel', hint:'The driver turns it to steer.',
      learn:'The steering wheel is inside the cabin, right in front of the driver. Turning it swings the front wheels left and right so the car goes where the driver points it.' }
  ],

  // ---- GAME 3: HOW CARS WORK (systems quiz) ----
  HOWITWORKS: [
    { q:'What does an engine actually do?', choices:['Burns fuel to create power that turns the wheels','Stores electricity for the lights','Cools the car down','Cleans the air'], answer:0,
      explain:'The engine mixes a little fuel with air inside sealed spaces called cylinders, then a spark sets off a tiny explosion. That explosion shoves a piston down, and the pistons spin a shaft (the crankshaft) that runs through the transmission to the wheels. Thousands of these little explosions a minute add up to the power that moves the car.' },
    { q:'What is the job of the battery?', choices:['To start the engine and power the electronics','To make the car go fast','To cool the engine','To hold gasoline'], answer:0,
      explain:'The battery’s number-one job is the big burst of electricity needed to crank the engine when you turn the key. It also powers the lights, radio, and computers when the engine is off. Once the engine is running, the alternator takes over and recharges the battery — so a healthy battery and a healthy alternator work as a team.' },
    { q:'How do the brakes stop the car?', choices:['Pads squeeze a spinning disc to slow the wheels','They pour water on the tires','They turn off the engine','They let air out of the tires'], answer:0,
      explain:'When you press the brake pedal, it pushes fluid through hoses that squeeze a clamp (the caliper) at each wheel. The clamp presses brake pads hard against a spinning metal disc. All that rubbing is friction, and friction turns the car’s motion into heat — which is why the car slows down and the brakes get hot.' },
    { q:'Why does an engine need oil?', choices:['To keep metal parts slippery so they don’t grind','To make the fuel burn','To fill the tires','To clean the windshield'], answer:0,
      explain:'Inside an engine, metal parts move incredibly fast and would grind themselves to pieces without protection. Oil forms a slippery film so those parts glide instead of scraping. It also carries away heat and traps dirt. That’s why cars need regular oil changes — over time the oil gets dirty and stops protecting as well.' },
    { q:'What does a radiator do?', choices:['Cools the engine using coolant and air','Makes the engine hotter','Powers the headlights','Steers the car'], answer:0,
      explain:'Engines make a huge amount of heat from all those little explosions. Liquid coolant flows through passages in the engine, soaks up the heat, and carries it to the radiator at the front of the car. Air blowing through the radiator’s thin fins cools the coolant back down, and then it loops around to do it all again.' },
    { q:'What are spark plugs for?', choices:['They make a spark that lights the fuel','They pump the gas','They hold the wheels on','They clean the oil'], answer:0,
      explain:'Each cylinder needs its fuel-and-air mix lit at exactly the right moment, and that’s the spark plug’s job. It snaps a tiny electric spark across a small gap, igniting the mixture so it explodes and pushes the piston. No spark means no explosion, no push, and a cylinder that just sits there dead — which makes the engine run rough.' },
    { q:'What does the alternator do while you drive?', choices:['Recharges the battery and powers the car','Fills the gas tank','Cools the brakes','Turns the steering wheel'], answer:0,
      explain:'The spinning engine turns a belt, and that belt spins the alternator, which is a little electricity generator. It makes fresh power to refill the battery and run everything electrical at once. This is the reason your battery doesn’t die after a long drive — but if the alternator fails, the car slowly runs the battery flat and shuts down.' },
    { q:'What is the transmission’s job?', choices:['Choosing the right gear for speed and power','Making electricity','Filtering the air','Holding the doors on'], answer:0,
      explain:'Gears trade speed for strength, like on a bike. A low gear gives lots of pushing force to get a heavy car moving from a stop; a high gear lets the engine spin slowly and calmly while you cruise fast. The transmission holds all these gears and switches between them — automatically in most cars, or by hand in a “manual.”' },
    { q:'Why do tires have grooves (tread)?', choices:['To grip the road and push away water','To look cool','To make noise','To save gas'], answer:0,
      explain:'On dry roads, rubber grips great. But in the rain, a smooth tire would float on top of the water and slide — that’s dangerous. The grooves (tread) give the water somewhere to escape, so the rubber can still press down and grip the road. As tread wears down flat, tires lose their grip in the wet, which is why they get replaced.' },
    { q:'What does the fuel pump do?', choices:['Pushes gas from the tank to the engine','Pumps air into the tires','Pumps water onto the windshield','Pumps oil into the brakes'], answer:0,
      explain:'The gas is stored in a tank at the back of the car, but the engine that burns it is up front. The fuel pump — usually sitting right inside the tank — pushes gasoline through a long line so the engine always has a steady supply. If the pump fails, the engine can crank all day but never start, because no fuel is reaching it.' },
    { q:'Where does an electric car get its power instead of gasoline?', choices:['A big rechargeable battery pack','A bigger radiator','More spark plugs','A second muffler'], answer:0,
      explain:'An electric car skips the gas engine entirely. Instead, a large battery pack — usually spread across the floor of the car — stores electricity you charge from a plug. That power feeds electric motors that spin the wheels directly. With no fuel burning, there are no spark plugs, no exhaust pipe, and nothing coming out the back.' },
    { q:'What is under-the-hood coolant (antifreeze) for?', choices:['Carrying heat away from the engine','Making the car smell nice','Cleaning the windows','Charging the battery'], answer:0,
      explain:'Coolant is the special liquid that circulates through the engine and radiator to move heat away and keep the engine at just the right temperature. It’s also called “antifreeze” because it’s mixed so it won’t freeze solid in winter or boil away in summer heat — both of which would leave the engine unprotected.' }
  ],

  // ---- GAME 4: FIX IT SHOP (symptom → which part to fix) ----
  // `answer` is a PARTS key; `choices` are PARTS keys (include the answer).
  FIXES: [
    { symptom:'You turn the key and hear click-click-click, but the engine won’t start. The lights are dim too.',
      answer:'battery', choices:['battery','tire','radiator','wiper'],
      explain:'That rapid clicking with dim lights is the classic sign of a dead or weak BATTERY. There isn’t enough power to spin the starter, so it just clicks. A jump-start from another car will usually get it going, but a battery this weak often needs replacing — and if it keeps dying, the alternator might not be recharging it.' },
    { symptom:'There’s a loud squealing sound every time you press the brake pedal.',
      answer:'brakes', choices:['brakes','headlight','fuelpump','airfilter'],
      explain:'Worn-out BRAKE pads have a little metal tab built in that starts to squeal on purpose once the pads get thin. It’s an early warning that says “replace me soon.” If you ignore it, the squeal turns into a grinding noise, and grinding metal-on-metal can ruin the more expensive disc behind the pad.' },
    { symptom:'The temperature gauge is in the red and steam is rising from under the hood.',
      answer:'radiator', choices:['radiator','seatbelt','sparkplug','tire'],
      explain:'Steam and a red-hot temperature gauge mean the engine is OVERHEATING — usually a RADIATOR or coolant problem, like low coolant or a leak. The safe move is to pull over and shut the engine off to let it cool. Driving an overheating engine even a little farther can warp or crack it into a very expensive repair.' },
    { symptom:'The engine runs rough and shaky, and the check-engine light came on.',
      answer:'sparkplug', choices:['sparkplug','steering','headlight','exhaust'],
      explain:'A rough, shaky idle plus a check-engine light often means a worn SPARK PLUG is “misfiring” — one cylinder isn’t lighting its fuel properly, so it skips beats like a runner with a limp. New spark plugs are a cheap, common fix that makes the engine smooth again and can even improve gas mileage.' },
    { symptom:'There’s a dark, slippery puddle under the engine when you pull out of the driveway.',
      answer:'oil', choices:['oil','tire','battery','wiper'],
      explain:'A dark, slick puddle under the front of the car is usually an OIL leak — often from a worn seal or gasket. It matters a lot: if the engine slowly loses oil and no one notices, the parts inside can grind and seize up. Checking the dipstick and topping up (then fixing the leak) protects the engine.' },
    { symptom:'At night you notice one side of the road ahead is dark and hard to see.',
      answer:'headlight', choices:['headlight','radiator','transmission','fuelpump'],
      explain:'When one side of the road is dark, a HEADLIGHT bulb has burned out. It’s a quick, cheap fix — but an important one, because a missing headlight makes it hard for you to see AND for other drivers to see you. A police officer will often pull you over for a burned-out light.' },
    { symptom:'The headlights are getting dim and the battery warning light is glowing while you drive.',
      answer:'alternator', choices:['alternator','brakes','airfilter','seatbelt'],
      explain:'Here’s the clue: things dim WHILE you’re driving, and the battery light is on. That points to the ALTERNATOR, not the battery — the alternator has stopped making electricity, so the car is draining the battery instead of recharging it. Left alone, everything fades and the car stalls once the battery is empty.' },
    { symptom:'The car shudders and won’t change gears smoothly when speeding up.',
      answer:'transmission', choices:['transmission','headlight','radiator','wiper'],
      explain:'Rough, jerky, or slipping gear changes point to the TRANSMISSION — the gearbox that decides how engine power reaches the wheels. Sometimes it just needs fresh transmission fluid; other times the gears or clutches inside are worn. Because it’s a big, complex part, catching problems early is much cheaper than a full rebuild.' },
    { symptom:'It’s pouring rain and you can’t see well — the glass in front stays streaky and blurry.',
      answer:'wiper', choices:['wiper','sparkplug','battery','exhaust'],
      explain:'Streaky, blurry glass in the rain means the WINDSHIELD WIPER blades are worn out. The rubber edge hardens and cracks over time, so instead of wiping clean it smears. New blades snap on in a couple of minutes and instantly make it easy to see — a small fix that’s a big safety deal.' },
    { symptom:'The steering wheel shakes and vibrates in your hands at highway speed.',
      answer:'tire', choices:['tire','oil','headlight','alternator'],
      explain:'A shake that appears at higher speeds usually means a TIRE problem — the tire is out of balance, worn unevenly, or has a bulge. A mechanic can “balance” the tires by adding tiny weights so they spin perfectly smooth again. Ignoring it wears the tire (and other parts) out faster.' },
    { symptom:'The engine is losing power and the check-engine light is on. The air box looks packed with dust and leaves.',
      answer:'airfilter', choices:['airfilter','seatbelt','brakes','radiator'],
      explain:'A clogged AIR FILTER chokes the engine — it can’t breathe in enough clean air to burn its fuel well, so it feels weak and sluggish. Swapping in a fresh filter is one of the easiest, cheapest fixes there is, and it restores power and can improve gas mileage right away.' },
    { symptom:'The engine cranks over and over but never catches, and the fuel gauge shows plenty of gas.',
      answer:'fuelpump', choices:['fuelpump','headlight','tire','wiper'],
      explain:'Cranking with no start, even though the tank is full, is a classic FUEL PUMP clue: the pump isn’t pushing gasoline up to the engine, so there’s spark but nothing to burn. (A helpful trick — many pumps make a quiet “whirr” from the back of the car for a second when you first turn the key. Silence can mean a dead pump.)' }
  ],

  // ---- GAME 5: DASHBOARD DETECTIVE (warning light → what it means) ----
  // `key` matches CARART.light(). `did` adds an extra teaching note in the reveal.
  LIGHTS: [
    { key:'checkengine', name:'Check Engine', urgency:'soon',
      meaning:'The car’s computer noticed something wrong in the engine or the pollution-control system. It could be small (like a loose gas cap) or something that needs real attention.',
      action:'You can usually keep driving gently and get it checked soon. But if the light is FLASHING, that’s serious — ease off and get to a shop right away to avoid engine damage.',
      did:'A mechanic can plug a scanner into the car to read a “trouble code” that tells them exactly which part set off the light.',
      choices:['Something in the engine needs checking','You’re low on gas','A door is open','The radio is on'], answer:0 },
    { key:'oil', name:'Oil Pressure', urgency:'now',
      meaning:'The engine has lost oil pressure, which means its fast-moving metal parts might not be getting the slippery protection they need.',
      action:'Pull over safely and turn the engine off as soon as you can. Running an engine with no oil pressure — even for a short time — can destroy it.',
      did:'This light is NOT the same as a scheduled oil change. It means low pressure right now, which is an emergency, not a “someday” reminder.',
      choices:['The engine’s oil pressure is low','The windshield fluid is low','The tires need air','The lights are on'], answer:0 },
    { key:'battery', name:'Charging System', urgency:'soon',
      meaning:'The battery isn’t charging the way it should while you drive. The most common cause is a failing alternator or a loose/broken belt.',
      action:'Get it checked soon. If it isn’t fixed, the battery will slowly drain and the car will lose power and stall — often at the worst time.',
      did:'Even though it looks like a battery, this light is usually really warning you about the ALTERNATOR that’s supposed to keep the battery full.',
      choices:['The battery isn’t charging right','The engine is too hot','You forgot your seat belt','The trunk is open'], answer:0 },
    { key:'temp', name:'Engine Temperature', urgency:'now',
      meaning:'The engine is running too hot — it’s overheating. Usually that means low coolant, a leak, or a cooling-system problem.',
      action:'Pull over and turn the engine off to let it cool down. Never open a hot radiator cap — the coolant is scalding and under pressure.',
      did:'Overheating is one of the few problems that can wreck an engine in just minutes, so this red light means “stop now,” not “finish the trip.”',
      choices:['The engine is overheating','You need an oil change','A tire is flat','The gas cap is loose'], answer:0 },
    { key:'tpms', name:'Tire Pressure', urgency:'soon',
      meaning:'At least one tire is low on air (or, less often, overfilled). Cars have sensors that watch the pressure in each tire.',
      action:'Add air to the low tire soon. Low tires wear out faster, waste gas, make the car handle poorly, and can even blow out.',
      did:'The little symbol is shaped like a cross-section of a tire with an exclamation point inside it — once you know that, it’s easy to spot.',
      choices:['A tire is low on air','The oil is dirty','The battery is dead','The brakes are worn'], answer:0 },
    { key:'brake', name:'Brake Warning', urgency:'now',
      meaning:'Either the parking brake is still on, or the brake system needs attention — often low brake fluid, which the brakes need to work.',
      action:'First make sure the parking brake is all the way down. If the light stays on, get the brakes checked right away — brakes are not something to drive around with when they’re warning you.',
      did:'Good brakes are pushed by fluid, not just cables. If the fluid gets low (sometimes from a leak or worn pads), this light comes on.',
      choices:['The brake system needs attention','A window is down','The AC is broken','You’re low on gas'], answer:0 },
    { key:'fuel', name:'Low Fuel', urgency:'soon',
      meaning:'You’re running low on gasoline and should fill up before the tank runs dry.',
      action:'Find a gas station soon. Running completely empty can leave you stranded and can even overheat and damage the fuel pump that sits inside the tank.',
      did:'Many cars have a tiny arrow next to the fuel light that points to the side of the car the gas cap is on — super handy at a new gas station.',
      choices:['You’re low on gas','The engine is overheating','A seat belt is unbuckled','The oil is low'], answer:0 },
    { key:'seatbelt', name:'Seat Belt Reminder', urgency:'now',
      meaning:'Someone in the car hasn’t buckled their seat belt yet.',
      action:'Buckle up before the car starts moving. It’s the single most important thing you can do to stay safe in a crash — and it’s the law.',
      did:'Many cars also chime or beep with this light, and some won’t stop until every passenger the car detects is buckled in.',
      choices:['A seat belt isn’t buckled','The engine needs oil','A tire is flat','The lights are off'], answer:0 },
    { key:'abs', name:'Anti-Lock Brakes (ABS)', urgency:'soon',
      meaning:'The anti-lock braking system has a fault. ABS is the feature that keeps the wheels from locking up and skidding during a hard stop.',
      action:'Your normal brakes still work, so you can drive carefully, but the anti-skid help may be switched off. Get it checked soon, especially before bad weather.',
      did:'ABS is why you can slam the brakes on a modern car and still steer around a hazard instead of sliding straight ahead.',
      choices:['The anti-skid brake system needs checking','The radio is broken','You’re low on gas','A door is open'], answer:0 },
    { key:'airbag', name:'Airbag', urgency:'soon',
      meaning:'The airbag safety system has detected a fault somewhere in itself.',
      action:'Get it checked soon. The worry is that the airbag might not inflate in a crash — or, rarely, could go off when it shouldn’t.',
      did:'Airbags work TOGETHER with seat belts, not instead of them. The belt holds you in place so the airbag can cushion you correctly.',
      choices:['The airbag system has a fault','The trunk is open','The oil is low','The wipers are on'], answer:0 }
  ],

  // ---- QUICK VERSIONS: a one-line "short version" shown at the top of each
  // reveal, so younger kids get the gist before the full explanation. ----
  QUICK: {
    part: {
      engine:'Burns fuel to make the power that turns the wheels.',
      battery:'Stores the electricity that starts the car.',
      tire:'The rubber part that grips the road.',
      brakes:'Squeezes the wheels to slow and stop the car.',
      sparkplug:'Lights the fuel with a tiny spark.',
      radiator:'Keeps the engine from overheating.',
      oil:'Slippery liquid that protects the engine.',
      alternator:'Recharges the battery while you drive.',
      steering:'The wheel that turns the car left and right.',
      seatbelt:'Holds you safely in your seat.',
      headlight:'Lights up the road at night.',
      transmission:'The gearbox that sends power to the wheels.',
      exhaust:'Sends waste gases out the back — and quiets the engine.',
      airfilter:'Cleans the air going into the engine.',
      wiper:'Wipes rain and snow off the windshield.',
      fuelpump:'Pushes gas from the tank up to the engine.'
    },
    diagram: {
      engine:'The “heart” up front that makes the power.',
      battery:'Front corner — it starts the car.',
      radiator:'Very front — it cools the engine.',
      headlight:'Front corners — they light the road.',
      brakes:'Behind each wheel — they stop the car.',
      fueltank:'Low in the back — it holds the gas.',
      exhaust:'Runs underneath to the back.',
      steering:'In the cabin, in front of the driver.'
    },
    work: [
      'Tiny explosions push pistons that spin the wheels.',
      'It starts the engine and powers the electronics.',
      'Pads squeeze a disc — the rubbing slows the car.',
      'It keeps engine parts slippery so they don’t grind.',
      'It carries engine heat away and cools it with air.',
      'It sparks to light the fuel at the perfect moment.',
      'The engine spins it to recharge the battery.',
      'Gears trade speed for power, like on a bike.',
      'The grooves push rain away so tires keep their grip.',
      'It pushes gas from the tank up to the engine.',
      'A big battery pack powers electric motors.',
      'It carries heat away to keep the engine cool.'
    ],
    fix: {
      battery:'It’s the BATTERY — it’s dead or weak.',
      brakes:'It’s the BRAKES — the pads are worn out.',
      radiator:'It’s the RADIATOR — the engine is overheating.',
      sparkplug:'It’s a SPARK PLUG — one cylinder is misfiring.',
      oil:'It’s an OIL leak.',
      headlight:'It’s a HEADLIGHT — a bulb burned out.',
      alternator:'It’s the ALTERNATOR — it stopped charging.',
      transmission:'It’s the TRANSMISSION — the gears are slipping.',
      wiper:'It’s the WIPERS — the blades are worn out.',
      tire:'It’s a TIRE — it’s out of balance.',
      airfilter:'It’s the AIR FILTER — it’s clogged.',
      fuelpump:'It’s the FUEL PUMP — no gas is reaching the engine.'
    },
    light: {
      checkengine:'Get the engine checked soon.',
      oil:'Low oil pressure — stop the engine now.',
      battery:'The battery isn’t charging — check it soon.',
      temp:'The engine is overheating — pull over now.',
      tpms:'A tire is low on air — add some soon.',
      brake:'The brakes need attention — check now.',
      fuel:'You’re low on gas — fill up soon.',
      seatbelt:'Buckle your seat belt before driving.',
      abs:'The anti-skid brakes need checking.',
      airbag:'The airbag system has a fault.'
    }
  }
};
