// Greek & Latin roots, prefixes, and suffixes — "the math facts of reading."
// Each entry: { part, type: 'prefix'|'root'|'suffix', origin: 'Greek'|'Latin', meaning, examples: [words] }
window.ROOTS = [
  // ---- PREFIXES ----
  { part: 'un-', type: 'prefix', origin: 'Latin', meaning: 'not / opposite of', examples: ['unhappy', 'unfair', 'undo'] },
  { part: 're-', type: 'prefix', origin: 'Latin', meaning: 'again / back', examples: ['replay', 'return', 'rebuild'] },
  { part: 'pre-', type: 'prefix', origin: 'Latin', meaning: 'before', examples: ['preview', 'predict', 'preheat'] },
  { part: 'dis-', type: 'prefix', origin: 'Latin', meaning: 'not / apart', examples: ['disagree', 'disappear', 'distrust'] },
  { part: 'mis-', type: 'prefix', origin: 'Latin', meaning: 'wrong / bad', examples: ['misspell', 'mistake', 'misuse'] },
  { part: 'sub-', type: 'prefix', origin: 'Latin', meaning: 'under / below', examples: ['submarine', 'subway', 'submerge'] },
  { part: 'super-', type: 'prefix', origin: 'Latin', meaning: 'above / beyond', examples: ['superhero', 'superb', 'supervise'] },
  { part: 'trans-', type: 'prefix', origin: 'Latin', meaning: 'across / through', examples: ['transport', 'transfer', 'translate'] },
  { part: 'inter-', type: 'prefix', origin: 'Latin', meaning: 'between / among', examples: ['interstate', 'international', 'interact'] },
  { part: 'anti-', type: 'prefix', origin: 'Greek', meaning: 'against', examples: ['antifreeze', 'antibiotic', 'antisocial'] },
  { part: 'auto-', type: 'prefix', origin: 'Greek', meaning: 'self', examples: ['automatic', 'autograph', 'autobiography'] },
  { part: 'tele-', type: 'prefix', origin: 'Greek', meaning: 'far / distant', examples: ['telephone', 'television', 'telescope'] },
  { part: 'micro-', type: 'prefix', origin: 'Greek', meaning: 'small', examples: ['microscope', 'microchip', 'microwave'] },
  { part: 'macro-', type: 'prefix', origin: 'Greek', meaning: 'large', examples: ['macroeconomics', 'macrocosm'] },
  { part: 'poly-', type: 'prefix', origin: 'Greek', meaning: 'many', examples: ['polygon', 'polygamy', 'polyglot'] },
  { part: 'mono-', type: 'prefix', origin: 'Greek', meaning: 'one / single', examples: ['monorail', 'monotone', 'monopoly'] },
  { part: 'uni-', type: 'prefix', origin: 'Latin', meaning: 'one', examples: ['unicycle', 'uniform', 'unicorn'] },
  { part: 'bi-', type: 'prefix', origin: 'Latin', meaning: 'two', examples: ['bicycle', 'bilingual', 'biweekly'] },
  { part: 'tri-', type: 'prefix', origin: 'Latin', meaning: 'three', examples: ['triangle', 'tricycle', 'trio'] },
  { part: 'hyper-', type: 'prefix', origin: 'Greek', meaning: 'over / excessive', examples: ['hyperactive', 'hyperlink'] },
  { part: 'hypo-', type: 'prefix', origin: 'Greek', meaning: 'under / less than', examples: ['hypodermic', 'hypothermia'] },
  { part: 'ex-', type: 'prefix', origin: 'Latin', meaning: 'out of / former', examples: ['exit', 'exhale', 'export'] },
  { part: 'in-/im-', type: 'prefix', origin: 'Latin', meaning: 'not', examples: ['invisible', 'impossible', 'inactive'] },
  { part: 'non-', type: 'prefix', origin: 'Latin', meaning: 'not', examples: ['nonfiction', 'nonstop', 'nonsense'] },
  { part: 'semi-', type: 'prefix', origin: 'Latin', meaning: 'half / partly', examples: ['semicircle', 'semifinal'] },
  { part: 'co-', type: 'prefix', origin: 'Latin', meaning: 'together / with', examples: ['cooperate', 'copilot', 'coauthor'] },
  { part: 'de-', type: 'prefix', origin: 'Latin', meaning: 'reverse / remove', examples: ['deactivate', 'defrost', 'derail'] },
  { part: 'post-', type: 'prefix', origin: 'Latin', meaning: 'after', examples: ['postpone', 'postwar', 'postscript'] },
  { part: 'over-', type: 'prefix', origin: 'English', meaning: 'too much / above', examples: ['overeat', 'overtime', 'overhead'] },
  { part: 'under-', type: 'prefix', origin: 'English', meaning: 'too little / below', examples: ['underground', 'undercook'] },

  // ---- ROOTS ----
  { part: 'bio', type: 'root', origin: 'Greek', meaning: 'life', examples: ['biology', 'biography', 'biodegradable'] },
  { part: 'port', type: 'root', origin: 'Latin', meaning: 'carry', examples: ['transport', 'export', 'portable'] },
  { part: 'dict', type: 'root', origin: 'Latin', meaning: 'speak / say', examples: ['predict', 'dictionary', 'verdict'] },
  { part: 'spect/spec', type: 'root', origin: 'Latin', meaning: 'see / look', examples: ['spectator', 'inspect', 'spectacle'] },
  { part: 'scrib/script', type: 'root', origin: 'Latin', meaning: 'write', examples: ['describe', 'script', 'manuscript'] },
  { part: 'rupt', type: 'root', origin: 'Latin', meaning: 'break', examples: ['interrupt', 'erupt', 'rupture'] },
  { part: 'struct', type: 'root', origin: 'Latin', meaning: 'build', examples: ['construct', 'structure', 'destruction'] },
  { part: 'tract', type: 'root', origin: 'Latin', meaning: 'pull / drag', examples: ['tractor', 'attract', 'subtract'] },
  { part: 'vid/vis', type: 'root', origin: 'Latin', meaning: 'see', examples: ['video', 'visible', 'television'] },
  { part: 'aud', type: 'root', origin: 'Latin', meaning: 'hear', examples: ['audio', 'audience', 'auditorium'] },
  { part: 'mit/miss', type: 'root', origin: 'Latin', meaning: 'send', examples: ['transmit', 'mission', 'dismiss'] },
  { part: 'ject', type: 'root', origin: 'Latin', meaning: 'throw', examples: ['project', 'reject', 'inject'] },
  { part: 'duc/duct', type: 'root', origin: 'Latin', meaning: 'lead', examples: ['conduct', 'induce', 'reduce'] },
  { part: 'fac/fact', type: 'root', origin: 'Latin', meaning: 'make / do', examples: ['factory', 'manufacture', 'satisfaction'] },
  { part: 'cred', type: 'root', origin: 'Latin', meaning: 'believe', examples: ['credit', 'incredible', 'credible'] },
  { part: 'fer', type: 'root', origin: 'Latin', meaning: 'carry / bear', examples: ['transfer', 'refer', 'suffer'] },
  { part: 'flect/flex', type: 'root', origin: 'Latin', meaning: 'bend', examples: ['reflect', 'flexible', 'deflect'] },
  { part: 'gen', type: 'root', origin: 'Greek', meaning: 'birth / produce', examples: ['generate', 'genetics', 'genesis'] },
  { part: 'graph', type: 'root', origin: 'Greek', meaning: 'write / draw', examples: ['autograph', 'photograph', 'graphic'] },
  { part: 'log/logo', type: 'root', origin: 'Greek', meaning: 'word / study of', examples: ['dialogue', 'geology', 'logic'] },
  { part: 'meter/metr', type: 'root', origin: 'Greek', meaning: 'measure', examples: ['thermometer', 'diameter', 'metric'] },
  { part: 'path', type: 'root', origin: 'Greek', meaning: 'feeling / suffering', examples: ['sympathy', 'empathy', 'pathetic'] },
  { part: 'phon', type: 'root', origin: 'Greek', meaning: 'sound', examples: ['telephone', 'symphony', 'microphone'] },
  { part: 'photo', type: 'root', origin: 'Greek', meaning: 'light', examples: ['photograph', 'photosynthesis'] },
  { part: 'pod/ped', type: 'root', origin: 'Greek/Latin', meaning: 'foot', examples: ['tripod', 'pedal', 'pedestrian'] },
  { part: 'scope', type: 'root', origin: 'Greek', meaning: 'see / view', examples: ['telescope', 'microscope', 'periscope'] },
  { part: 'therm', type: 'root', origin: 'Greek', meaning: 'heat', examples: ['thermometer', 'thermal', 'thermos'] },
  { part: 'chron', type: 'root', origin: 'Greek', meaning: 'time', examples: ['chronological', 'synchronize', 'chronic'] },
  { part: 'geo', type: 'root', origin: 'Greek', meaning: 'earth', examples: ['geography', 'geology', 'geometry'] },
  { part: 'hydro', type: 'root', origin: 'Greek', meaning: 'water', examples: ['hydrant', 'dehydrate', 'hydropower'] },
  { part: 'astro', type: 'root', origin: 'Greek', meaning: 'star', examples: ['astronaut', 'astronomy', 'asteroid'] },
  { part: 'dem', type: 'root', origin: 'Greek', meaning: 'people', examples: ['democracy', 'epidemic', 'demographic'] },
  { part: 'morph', type: 'root', origin: 'Greek', meaning: 'shape / form', examples: ['metamorphosis', 'amorphous'] },
  { part: 'psych', type: 'root', origin: 'Greek', meaning: 'mind / soul', examples: ['psychology', 'psychic'] },
  { part: 'soph', type: 'root', origin: 'Greek', meaning: 'wisdom', examples: ['philosophy', 'sophisticated'] },
  { part: 'hetero', type: 'root', origin: 'Greek', meaning: 'different', examples: ['heterogeneous'] },
  { part: 'homo', type: 'root', origin: 'Greek', meaning: 'same', examples: ['homogeneous', 'homonym'] },
  { part: 'neo', type: 'root', origin: 'Greek', meaning: 'new', examples: ['neon', 'neonatal'] },
  { part: 'pan', type: 'root', origin: 'Greek', meaning: 'all', examples: ['panorama', 'pandemic'] },

  // ---- SUFFIXES ----
  { part: '-tion/-sion', type: 'suffix', origin: 'Latin', meaning: 'act or state of', examples: ['action', 'decision', 'creation'] },
  { part: '-able/-ible', type: 'suffix', origin: 'Latin', meaning: 'capable of / able to', examples: ['readable', 'flexible', 'washable'] },
  { part: '-er/-or', type: 'suffix', origin: 'English/Latin', meaning: 'one who does something', examples: ['teacher', 'actor', 'sailor'] },
  { part: '-ful', type: 'suffix', origin: 'English', meaning: 'full of', examples: ['joyful', 'careful', 'colorful'] },
  { part: '-less', type: 'suffix', origin: 'English', meaning: 'without', examples: ['fearless', 'homeless', 'careless'] },
  { part: '-ment', type: 'suffix', origin: 'Latin', meaning: 'result or act of', examples: ['enjoyment', 'movement', 'agreement'] },
  { part: '-ology', type: 'suffix', origin: 'Greek', meaning: 'study of', examples: ['biology', 'zoology', 'geology'] },
  { part: '-phobia', type: 'suffix', origin: 'Greek', meaning: 'fear of', examples: ['arachnophobia', 'claustrophobia'] },
  { part: '-graphy', type: 'suffix', origin: 'Greek', meaning: 'writing or recording', examples: ['photography', 'geography'] },
  { part: '-ism', type: 'suffix', origin: 'Greek', meaning: 'belief or practice', examples: ['heroism', 'tourism', 'optimism'] },
  { part: '-ist', type: 'suffix', origin: 'Greek', meaning: 'one who practices', examples: ['artist', 'scientist', 'dentist'] },
  { part: '-ize', type: 'suffix', origin: 'Greek', meaning: 'to make', examples: ['organize', 'realize', 'modernize'] },
  { part: '-ous', type: 'suffix', origin: 'Latin', meaning: 'full of', examples: ['dangerous', 'famous', 'joyous'] },
  { part: '-ive', type: 'suffix', origin: 'Latin', meaning: 'tending to', examples: ['active', 'creative', 'protective'] }
];
