// Greek & Latin roots, prefixes, and suffixes — "the math facts of reading."
// Each entry: { part, type: 'prefix'|'root'|'suffix', origin, meaning,
//   examples: [ [word, definition], ... ] }
window.ROOTS = [
  // ---- PREFIXES ----
  { part: 'un-', type: 'prefix', origin: 'Latin', meaning: 'not / opposite of', examples: [['unhappy','not happy'],['unfair','not fair'],['undo','reverse an action']] },
  { part: 're-', type: 'prefix', origin: 'Latin', meaning: 'again / back', examples: [['replay','play again'],['return','come back'],['rebuild','build again']] },
  { part: 'pre-', type: 'prefix', origin: 'Latin', meaning: 'before', examples: [['preview','view before'],['predict','say before it happens'],['preheat','heat before']] },
  { part: 'dis-', type: 'prefix', origin: 'Latin', meaning: 'not / apart', examples: [['disagree','not agree'],['disappear','stop being visible'],['distrust','not trust']] },
  { part: 'mis-', type: 'prefix', origin: 'Latin', meaning: 'wrong / bad', examples: [['misspell','spell wrong'],['mistake','a wrong idea or action'],['misuse','use wrongly']] },
  { part: 'sub-', type: 'prefix', origin: 'Latin', meaning: 'under / below', examples: [['submarine','a ship that travels underwater'],['subway','an underground train'],['submerge','put under water']] },
  { part: 'super-', type: 'prefix', origin: 'Latin', meaning: 'above / beyond', examples: [['superhero','a hero with amazing powers'],['superb','better than good; excellent'],['supervise','oversee others’ work']] },
  { part: 'trans-', type: 'prefix', origin: 'Latin', meaning: 'across / through', examples: [['transport','carry across a distance'],['transfer','move from one place to another'],['translate','change into another language']] },
  { part: 'inter-', type: 'prefix', origin: 'Latin', meaning: 'between / among', examples: [['interstate','between states'],['international','between nations'],['interact','act with one another']] },
  { part: 'anti-', type: 'prefix', origin: 'Greek', meaning: 'against', examples: [['antifreeze','liquid that stops freezing'],['antibiotic','medicine that fights germs'],['antisocial','avoiding other people']] },
  { part: 'auto-', type: 'prefix', origin: 'Greek', meaning: 'self', examples: [['automatic','working by itself'],['autograph','a signature written by oneself'],['autobiography','the story of your own life']] },
  { part: 'tele-', type: 'prefix', origin: 'Greek', meaning: 'far / distant', examples: [['telephone','device for talking over a distance'],['television','see pictures from far away'],['telescope','tool to see distant things']] },
  { part: 'micro-', type: 'prefix', origin: 'Greek', meaning: 'small', examples: [['microscope','tool to see tiny things'],['microchip','a tiny computer part'],['microwave','oven that uses tiny waves']] },
  { part: 'macro-', type: 'prefix', origin: 'Greek', meaning: 'large', examples: [['macroeconomics','study of the whole economy'],['macrocosm','the large-scale universe']] },
  { part: 'poly-', type: 'prefix', origin: 'Greek', meaning: 'many', examples: [['polygon','a shape with many sides'],['polygamy','having many spouses'],['polyglot','someone who speaks many languages']] },
  { part: 'mono-', type: 'prefix', origin: 'Greek', meaning: 'one / single', examples: [['monorail','a train on one rail'],['monotone','a single, unchanging tone'],['monopoly','control by one company']] },
  { part: 'uni-', type: 'prefix', origin: 'Latin', meaning: 'one', examples: [['unicycle','a cycle with one wheel'],['uniform','one same outfit for all'],['unicorn','a horse with one horn']] },
  { part: 'bi-', type: 'prefix', origin: 'Latin', meaning: 'two', examples: [['bicycle','a cycle with two wheels'],['bilingual','speaking two languages'],['biweekly','every two weeks']] },
  { part: 'tri-', type: 'prefix', origin: 'Latin', meaning: 'three', examples: [['triangle','a shape with three angles'],['tricycle','a cycle with three wheels'],['trio','a group of three']] },
  { part: 'hyper-', type: 'prefix', origin: 'Greek', meaning: 'over / excessive', examples: [['hyperactive','extremely active'],['hyperlink','a link that jumps you elsewhere']] },
  { part: 'hypo-', type: 'prefix', origin: 'Greek', meaning: 'under / less than', examples: [['hypodermic','going under the skin'],['hypothermia','body temperature that is too low']] },
  { part: 'ex-', type: 'prefix', origin: 'Latin', meaning: 'out of / former', examples: [['exit','a way out'],['exhale','breathe out'],['export','send goods out of a country']] },
  { part: 'in-/im-', type: 'prefix', origin: 'Latin', meaning: 'not', examples: [['invisible','not able to be seen'],['impossible','not able to happen'],['inactive','not active']] },
  { part: 'non-', type: 'prefix', origin: 'Latin', meaning: 'not', examples: [['nonfiction','writing that is not made up'],['nonstop','without stopping'],['nonsense','words with no meaning']] },
  { part: 'semi-', type: 'prefix', origin: 'Latin', meaning: 'half / partly', examples: [['semicircle','half of a circle'],['semifinal','the round before the final']] },
  { part: 'co-', type: 'prefix', origin: 'Latin', meaning: 'together / with', examples: [['cooperate','work together'],['copilot','a second pilot'],['coauthor','a person who writes with another']] },
  { part: 'de-', type: 'prefix', origin: 'Latin', meaning: 'reverse / remove', examples: [['deactivate','turn off'],['defrost','remove frost; thaw'],['derail','go off the rails']] },
  { part: 'post-', type: 'prefix', origin: 'Latin', meaning: 'after', examples: [['postpone','put off until later'],['postwar','after a war'],['postscript','a note added after a letter']] },
  { part: 'over-', type: 'prefix', origin: 'English', meaning: 'too much / above', examples: [['overeat','eat too much'],['overtime','time worked beyond normal hours'],['overhead','above your head']] },
  { part: 'under-', type: 'prefix', origin: 'English', meaning: 'too little / below', examples: [['underground','below the ground'],['undercook','not cook enough']] },

  // ---- ROOTS ----
  { part: 'bio', type: 'root', origin: 'Greek', meaning: 'life', examples: [['biology','the study of living things'],['biography','the story of someone’s life'],['biodegradable','able to be broken down by living things']] },
  { part: 'port', type: 'root', origin: 'Latin', meaning: 'carry', examples: [['transport','carry across a distance'],['export','carry goods out of a country'],['portable','able to be carried']] },
  { part: 'dict', type: 'root', origin: 'Latin', meaning: 'speak / say', examples: [['predict','say what will happen'],['dictionary','a book of words and meanings'],['verdict','a spoken decision in court']] },
  { part: 'spect/spec', type: 'root', origin: 'Latin', meaning: 'see / look', examples: [['spectator','a person who watches'],['inspect','look at closely'],['spectacle','an impressive sight']] },
  { part: 'scrib/script', type: 'root', origin: 'Latin', meaning: 'write', examples: [['describe','tell about in words'],['script','the written words of a play'],['manuscript','a handwritten document']] },
  { part: 'rupt', type: 'root', origin: 'Latin', meaning: 'break', examples: [['interrupt','break into a conversation'],['erupt','burst out'],['rupture','a break or tear']] },
  { part: 'struct', type: 'root', origin: 'Latin', meaning: 'build', examples: [['construct','build something'],['structure','something that is built'],['destruction','the act of tearing down']] },
  { part: 'tract', type: 'root', origin: 'Latin', meaning: 'pull / drag', examples: [['tractor','a machine that pulls'],['attract','pull toward'],['subtract','take away']] },
  { part: 'vid/vis', type: 'root', origin: 'Latin', meaning: 'see', examples: [['video','moving pictures you can see'],['visible','able to be seen'],['television','device for seeing distant pictures']] },
  { part: 'aud', type: 'root', origin: 'Latin', meaning: 'hear', examples: [['audio','sound you can hear'],['audience','people who listen'],['auditorium','a hall for hearing performances']] },
  { part: 'mit/miss', type: 'root', origin: 'Latin', meaning: 'send', examples: [['transmit','send across'],['mission','a task someone is sent to do'],['dismiss','send away']] },
  { part: 'ject', type: 'root', origin: 'Latin', meaning: 'throw', examples: [['project','throw or cast forward'],['reject','throw back; refuse'],['inject','throw fluid into the body']] },
  { part: 'duc/duct', type: 'root', origin: 'Latin', meaning: 'lead', examples: [['conduct','lead or guide'],['induce','lead to cause'],['reduce','lead down; make less']] },
  { part: 'fac/fact', type: 'root', origin: 'Latin', meaning: 'make / do', examples: [['factory','a place where things are made'],['manufacture','to make goods'],['satisfaction','the feeling of being made content']] },
  { part: 'cred', type: 'root', origin: 'Latin', meaning: 'believe', examples: [['credit','trust that someone will pay'],['incredible','too amazing to believe'],['credible','able to be believed']] },
  { part: 'fer', type: 'root', origin: 'Latin', meaning: 'carry / bear', examples: [['transfer','carry from one place to another'],['refer','carry attention to'],['suffer','bear something painful']] },
  { part: 'flect/flex', type: 'root', origin: 'Latin', meaning: 'bend', examples: [['reflect','bend back, as light'],['flexible','able to bend'],['deflect','bend away']] },
  { part: 'gen', type: 'root', origin: 'Greek', meaning: 'birth / produce', examples: [['generate','produce or create'],['genetics','the study of inherited traits'],['genesis','the beginning or origin']] },
  { part: 'graph', type: 'root', origin: 'Greek', meaning: 'write / draw', examples: [['autograph','a signature'],['photograph','a picture made with light'],['graphic','a drawn image']] },
  { part: 'log/logo', type: 'root', origin: 'Greek', meaning: 'word / study of', examples: [['dialogue','words spoken between people'],['geology','the study of the earth'],['logic','reasoning with words and ideas']] },
  { part: 'meter/metr', type: 'root', origin: 'Greek', meaning: 'measure', examples: [['thermometer','a tool that measures heat'],['diameter','the measure across a circle'],['metric','a system of measurement']] },
  { part: 'path', type: 'root', origin: 'Greek', meaning: 'feeling / suffering', examples: [['sympathy','sharing another’s feelings'],['empathy','understanding another’s feelings'],['pathetic','causing pity']] },
  { part: 'phon', type: 'root', origin: 'Greek', meaning: 'sound', examples: [['telephone','device for sound over a distance'],['symphony','many sounds played together'],['microphone','a tool that captures sound']] },
  { part: 'photo', type: 'root', origin: 'Greek', meaning: 'light', examples: [['photograph','a picture made with light'],['photosynthesis','plants making food from light']] },
  { part: 'pod/ped', type: 'root', origin: 'Greek/Latin', meaning: 'foot', examples: [['tripod','a three-footed stand'],['pedal','a lever pushed by the foot'],['pedestrian','a person traveling on foot']] },
  { part: 'scope', type: 'root', origin: 'Greek', meaning: 'see / view', examples: [['telescope','a tool to view distant things'],['microscope','a tool to view tiny things'],['periscope','a tool to see around obstacles']] },
  { part: 'therm', type: 'root', origin: 'Greek', meaning: 'heat', examples: [['thermometer','a tool that measures heat'],['thermal','relating to heat'],['thermos','a container that keeps heat in']] },
  { part: 'chron', type: 'root', origin: 'Greek', meaning: 'time', examples: [['chronological','arranged in time order'],['synchronize','make happen at the same time'],['chronic','lasting a long time']] },
  { part: 'geo', type: 'root', origin: 'Greek', meaning: 'earth', examples: [['geography','the study of the earth’s features'],['geology','the study of the earth’s rocks'],['geometry','math of shapes and earth measures']] },
  { part: 'hydro', type: 'root', origin: 'Greek', meaning: 'water', alt: ['hydr'], examples: [['hydrant','a water pipe for firefighters'],['dehydrate','remove water'],['hydropower','power made from moving water']] },
  { part: 'astro', type: 'root', origin: 'Greek', meaning: 'star', alt: ['aster'], examples: [['astronaut','a person who travels among the stars'],['astronomy','the study of stars and space'],['asteroid','a small rocky body in space']] },
  { part: 'dem', type: 'root', origin: 'Greek', meaning: 'people', examples: [['democracy','rule by the people'],['epidemic','a disease spreading among people'],['demographic','a group of people with shared traits']] },
  { part: 'morph', type: 'root', origin: 'Greek', meaning: 'shape / form', examples: [['metamorphosis','a change in form'],['amorphous','having no clear shape']] },
  { part: 'psych', type: 'root', origin: 'Greek', meaning: 'mind / soul', examples: [['psychology','the study of the mind'],['psychic','relating to the mind’s powers']] },
  { part: 'soph', type: 'root', origin: 'Greek', meaning: 'wisdom', examples: [['philosophy','the love of wisdom'],['sophisticated','showing worldly wisdom']] },
  { part: 'hetero', type: 'root', origin: 'Greek', meaning: 'different', examples: [['heterogeneous','made of different parts']] },
  { part: 'homo', type: 'root', origin: 'Greek', meaning: 'same', examples: [['homogeneous','made of the same parts'],['homonym','words that sound the same']] },
  { part: 'neo', type: 'root', origin: 'Greek', meaning: 'new', examples: [['neon','a bright “new” gas'],['neonatal','relating to a newborn']] },
  { part: 'pan', type: 'root', origin: 'Greek', meaning: 'all', examples: [['panorama','a wide view of everything around'],['pandemic','a disease affecting people everywhere']] },

  // ---- SUFFIXES ----
  { part: '-tion/-sion', type: 'suffix', origin: 'Latin', meaning: 'act or state of', examples: [['action','the act of doing'],['decision','the act of deciding'],['creation','the act of creating']] },
  { part: '-able/-ible', type: 'suffix', origin: 'Latin', meaning: 'capable of / able to', examples: [['readable','able to be read'],['flexible','able to bend'],['washable','able to be washed']] },
  { part: '-er/-or', type: 'suffix', origin: 'English/Latin', meaning: 'one who does something', examples: [['teacher','one who teaches'],['actor','one who acts'],['sailor','one who sails']] },
  { part: '-ful', type: 'suffix', origin: 'English', meaning: 'full of', examples: [['joyful','full of joy'],['careful','full of care'],['colorful','full of color']] },
  { part: '-less', type: 'suffix', origin: 'English', meaning: 'without', examples: [['fearless','without fear'],['homeless','without a home'],['careless','without care']] },
  { part: '-ment', type: 'suffix', origin: 'Latin', meaning: 'result or act of', examples: [['enjoyment','the state of enjoying'],['movement','the act of moving'],['agreement','the result of agreeing']] },
  { part: '-ology', type: 'suffix', origin: 'Greek', meaning: 'study of', examples: [['biology','the study of life'],['zoology','the study of animals'],['geology','the study of the earth']] },
  { part: '-phobia', type: 'suffix', origin: 'Greek', meaning: 'fear of', examples: [['arachnophobia','fear of spiders'],['claustrophobia','fear of tight spaces']] },
  { part: '-graphy', type: 'suffix', origin: 'Greek', meaning: 'writing or recording', examples: [['photography','recording images with light'],['geography','describing the earth']] },
  { part: '-ism', type: 'suffix', origin: 'Greek', meaning: 'belief or practice', examples: [['heroism','brave conduct'],['tourism','the practice of traveling for fun'],['optimism','the belief that things will be good']] },
  { part: '-ist', type: 'suffix', origin: 'Greek', meaning: 'one who practices', examples: [['artist','one who makes art'],['scientist','one who does science'],['dentist','one who cares for teeth']] },
  { part: '-ize', type: 'suffix', origin: 'Greek', meaning: 'to make', examples: [['organize','to make orderly'],['realize','to make real in the mind'],['modernize','to make modern']] },
  { part: '-ous', type: 'suffix', origin: 'Latin', meaning: 'full of', examples: [['dangerous','full of danger'],['famous','full of fame'],['joyous','full of joy']] },
  { part: '-ive', type: 'suffix', origin: 'Latin', meaning: 'tending to', examples: [['active','tending to act'],['creative','tending to create'],['protective','tending to protect']] }
];
