/* Food Explorer — data for the "look up a real food" section of Nutrition Quest.
 * Each food has serving/nutrition numbers, key nutrients + what they do, why it's
 * healthy or not, pros/cons, and a plain "what it does in your body" explanation.
 * rating: everyday | sometimes | treat.
 * PHOTO: realfood/<slug>/<slug>.jpg (each food has its own folder — to swap in a
 * new picture, just replace that file; a .png of the same name also works).
 * `q` is the Pexels search query the photo was fetched with.
 */
window.FOODX = [
  { slug:'apple', name:'Apple', group:'Fruit', rating:'everyday', q:'red apple fruit whole',
    serving:'1 medium (182 g)', calories:95,
    stats:[{k:'Carbs',v:'25 g'},{k:'Sugar',v:'19 g (natural)'},{k:'Fiber',v:'4 g'},{k:'Protein',v:'0.5 g'}],
    nutrients:[{n:'Fiber',does:'keeps you full and helps digestion'},{n:'Vitamin C',does:'heals cuts and fights germs'},{n:'Potassium',does:'helps your heart and muscles work'}],
    why:'A whole fruit — the sugar comes packaged with fiber and water, so it fuels you without a crash.',
    pros:['Fiber fills you up','Vitamin C and antioxidants','No added sugar','Crunchy and hydrating'],
    cons:['Skin can hold pesticide (wash it)','As juice, it loses the fiber'],
    body:'The fiber and water slow how fast the sugar reaches your blood, so you get steady energy instead of a sugar rush. Most of the fiber and antioxidants live in the skin.' },

  { slug:'banana', name:'Banana', group:'Fruit', rating:'everyday', q:'banana fruit',
    serving:'1 medium (118 g)', calories:105,
    stats:[{k:'Carbs',v:'27 g'},{k:'Sugar',v:'14 g (natural)'},{k:'Fiber',v:'3 g'},{k:'Protein',v:'1 g'}],
    nutrients:[{n:'Potassium',does:'steadies your heartbeat and muscles'},{n:'Vitamin B6',does:'turns food into energy'},{n:'Vitamin C',does:'protects your cells'}],
    why:'Portable quick energy plus potassium — great before or after moving around.',
    pros:['Fast, natural energy','High in potassium','Some fiber','Easy to digest'],
    cons:['More sugar than most fruit','Very ripe = even more sugar'],
    body:'The natural sugars give quick fuel while the fiber keeps it from spiking too hard. Potassium helps your muscles contract, which is why bananas are a classic snack for sports.' },

  { slug:'blueberries', name:'Blueberries', group:'Fruit', rating:'everyday', q:'fresh blueberries bowl',
    serving:'1 cup (148 g)', calories:84,
    stats:[{k:'Carbs',v:'21 g'},{k:'Sugar',v:'15 g (natural)'},{k:'Fiber',v:'4 g'},{k:'Protein',v:'1 g'}],
    nutrients:[{n:'Vitamin C',does:'fights germs and heals'},{n:'Vitamin K',does:'helps blood clot'},{n:'Antioxidants',does:'protect cells from damage'}],
    why:'One of the most antioxidant-packed foods, and low in calories for how filling it is.',
    pros:['Loaded with antioxidants','Low calorie','Good fiber','No prep needed'],
    cons:['Can be pricey','Fresh ones spoil fast'],
    body:'The deep-blue color comes from antioxidants called anthocyanins that mop up the "rust" (free radicals) your cells make. The fiber feeds the good bacteria in your gut.' },

  { slug:'avocado', name:'Avocado', group:'Fruit', rating:'everyday', q:'avocado halved',
    serving:'1/2 avocado (68 g)', calories:114,
    stats:[{k:'Fat',v:'10 g (healthy)'},{k:'Carbs',v:'6 g'},{k:'Fiber',v:'5 g'},{k:'Protein',v:'1 g'}],
    nutrients:[{n:'Healthy fat',does:'fuels you and helps absorb vitamins'},{n:'Fiber',does:'keeps you full and steady'},{n:'Potassium',does:'balances fluids and blood pressure'}],
    why:'Most of its calories are heart-healthy unsaturated fat, plus a lot of fiber — filling and nourishing.',
    pros:['Heart-healthy fats','Very filling','High fiber','Helps you absorb other vitamins'],
    cons:['High in calories, so watch the amount','Can be unripe or brown quickly'],
    body:'The unsaturated fat is the kind that helps your body soak up vitamins A, D, E, and K from other foods. It also digests slowly, so you stay full for hours.' },

  { slug:'broccoli', name:'Broccoli', group:'Vegetable', rating:'everyday', q:'broccoli florets',
    serving:'1 cup chopped (91 g)', calories:31,
    stats:[{k:'Carbs',v:'6 g'},{k:'Fiber',v:'2 g'},{k:'Protein',v:'3 g'},{k:'Sugar',v:'2 g'}],
    nutrients:[{n:'Vitamin C',does:'fights germs and heals cuts'},{n:'Vitamin K',does:'helps bones and clotting'},{n:'Fiber',does:'helps digestion'}],
    why:'Tons of vitamins for almost no calories — a nutrient bargain.',
    pros:['Packed with vitamin C and K','Very low calorie','Good fiber','Some plant protein'],
    cons:['Can cause gas for some people','Bitter if overcooked'],
    body:'Broccoli delivers more vitamin C per bite than an orange, plus fiber that feeds gut bacteria. Light steaming keeps the most vitamins; boiling washes some away.' },

  { slug:'carrot', name:'Carrot', group:'Vegetable', rating:'everyday', q:'bunch of carrots',
    serving:'1 medium (61 g)', calories:25,
    stats:[{k:'Carbs',v:'6 g'},{k:'Sugar',v:'3 g'},{k:'Fiber',v:'2 g'},{k:'Protein',v:'0.5 g'}],
    nutrients:[{n:'Vitamin A',does:'keeps your eyes and vision healthy'},{n:'Fiber',does:'helps digestion'},{n:'Vitamin K',does:'helps blood clot'}],
    why:'The classic eyes-and-skin veggie — crunchy, sweet, and barely any calories.',
    pros:['Great for eyes (vitamin A)','Naturally sweet, low calorie','Portable crunch','Good fiber'],
    cons:['Loses crunch when cooked','Dips can add lots of fat/sugar'],
    body:'Your body turns the orange pigment (beta-carotene) into vitamin A, which your eyes use to see in dim light. A little fat — like hummus or dressing — helps you absorb it.' },

  { slug:'spinach', name:'Spinach', group:'Vegetable', rating:'everyday', q:'fresh spinach leaves',
    serving:'2 cups raw (60 g)', calories:14,
    stats:[{k:'Carbs',v:'2 g'},{k:'Fiber',v:'1 g'},{k:'Protein',v:'2 g'},{k:'Iron',v:'1.6 mg'}],
    nutrients:[{n:'Vitamin K',does:'helps bones and blood clot'},{n:'Vitamin A',does:'protects eyes and skin'},{n:'Iron',does:'carries oxygen in your blood'},{n:'Folate',does:'builds new cells'}],
    why:'A leafy green that stacks vitamins, iron, and folate for almost zero calories.',
    pros:['Iron and folate','Huge vitamin K and A','Almost no calories','Easy to hide in smoothies'],
    cons:['Iron absorbs better with vitamin C','Wilts down to very little'],
    body:'The iron helps your red blood cells carry oxygen so you don’t feel tired. Pairing spinach with something high in vitamin C (like orange or pepper) helps your gut absorb that iron.' },

  { slug:'sweet_potato', name:'Sweet Potato', group:'Vegetable', rating:'everyday', q:'baked sweet potato',
    serving:'1 medium baked (130 g)', calories:112,
    stats:[{k:'Carbs',v:'26 g'},{k:'Fiber',v:'4 g'},{k:'Sugar',v:'5 g'},{k:'Protein',v:'2 g'}],
    nutrients:[{n:'Vitamin A',does:'keeps eyes and skin healthy'},{n:'Vitamin C',does:'fights germs'},{n:'Potassium',does:'balances fluids'},{n:'Fiber',does:'keeps you full'}],
    why:'A starchy vegetable, but full of fiber and vitamin A — steadier energy than white potato or fries.',
    pros:['Big dose of vitamin A','Good fiber','Naturally sweet','Filling, slow energy'],
    cons:['Still starchy (portion matters)','Fried or candied cancels the benefits'],
    body:'The fiber slows the starch down so your energy lasts longer than from fries or chips. The orange color is beta-carotene, the same eye-helper as in carrots.' },

  { slug:'chicken_breast', name:'Chicken Breast', group:'Protein', rating:'everyday', q:'grilled chicken breast plate',
    serving:'3 oz cooked (85 g)', calories:128,
    stats:[{k:'Protein',v:'26 g'},{k:'Fat',v:'3 g'},{k:'Carbs',v:'0 g'},{k:'Sodium',v:'44 mg'}],
    nutrients:[{n:'Protein',does:'builds and repairs muscle'},{n:'Niacin (B3)',does:'turns food into energy'},{n:'Vitamin B6',does:'supports brain and blood'},{n:'Selenium',does:'protects cells'}],
    why:'A lean protein powerhouse — lots of muscle-building protein with very little fat.',
    pros:['Very high protein','Low in fat','Keeps you full','Versatile'],
    cons:['Fried or breaded adds fat/salt','Dry if overcooked'],
    body:'The protein breaks into amino acids that rebuild your muscles after you move and play. Because it’s low in fat and carbs, it fills you up without a lot of extra calories — as long as it’s grilled or baked, not fried.' },

  { slug:'egg', name:'Egg', group:'Protein', rating:'everyday', q:'hard boiled eggs',
    serving:'1 large (50 g)', calories:72,
    stats:[{k:'Protein',v:'6 g'},{k:'Fat',v:'5 g'},{k:'Carbs',v:'0.4 g'},{k:'Cholesterol',v:'186 mg'}],
    nutrients:[{n:'Protein',does:'builds muscle and cells'},{n:'Choline',does:'helps your brain and memory'},{n:'Vitamin D',does:'helps bones'},{n:'Vitamin B12',does:'makes red blood cells'}],
    why:'One of the most complete foods — high-quality protein plus brain-helping choline, all for 72 calories.',
    pros:['Complete protein','Choline for the brain','Cheap and filling','Very versatile'],
    cons:['Yolk is high in cholesterol','Fried in butter/oil adds fat'],
    body:'Eggs have every amino acid your body needs, so they’re a "complete" protein for building cells. The yolk’s choline helps your brain send messages — useful for focus and memory.' },

  { slug:'salmon', name:'Salmon', group:'Protein', rating:'everyday', q:'cooked salmon fillet plate',
    serving:'3 oz cooked (85 g)', calories:175,
    stats:[{k:'Protein',v:'19 g'},{k:'Fat',v:'10 g (omega-3)'},{k:'Carbs',v:'0 g'},{k:'Vitamin D',v:'high'}],
    nutrients:[{n:'Omega-3 fat',does:'builds your brain and calms inflammation'},{n:'Protein',does:'repairs muscle'},{n:'Vitamin D',does:'helps bones and mood'},{n:'Vitamin B12',does:'makes blood and nerves'}],
    why:'A "brain food" — one of the best sources of omega-3 fats, plus protein and vitamin D.',
    pros:['Rich in omega-3 for the brain','High protein','Rare food source of vitamin D','Heart-healthy'],
    cons:['Can be pricey','Some fish carry a little mercury'],
    body:'The omega-3 fats actually become building material for your brain and eyes, and they help quiet inflammation (your body’s "swelling" response). The vitamin D helps your gut pull calcium in for bones.' },

  { slug:'black_beans', name:'Black Beans', group:'Protein', rating:'everyday', q:'black beans',
    serving:'1/2 cup cooked (86 g)', calories:114,
    stats:[{k:'Protein',v:'8 g'},{k:'Fiber',v:'7 g'},{k:'Carbs',v:'20 g'},{k:'Iron',v:'1.8 mg'}],
    nutrients:[{n:'Fiber',does:'keeps you full and steady'},{n:'Plant protein',does:'builds and repairs'},{n:'Iron',does:'carries oxygen in blood'},{n:'Folate',does:'builds new cells'}],
    why:'Protein AND fiber in one cheap package — filling, steady energy, and good for your gut.',
    pros:['Protein + fiber together','Very filling','Cheap','Good for gut bacteria'],
    cons:['Can cause gas at first','Canned ones can be high in salt (rinse them)'],
    body:'Beans are one of the few foods with lots of protein and lots of fiber, so they keep you full for a long time. The fiber feeds friendly gut bacteria, which keep your digestion happy.' },

  { slug:'almonds', name:'Almonds', group:'Nuts', rating:'everyday', q:'almonds nuts',
    serving:'1 oz, ~23 nuts (28 g)', calories:164,
    stats:[{k:'Fat',v:'14 g (healthy)'},{k:'Protein',v:'6 g'},{k:'Fiber',v:'4 g'},{k:'Carbs',v:'6 g'}],
    nutrients:[{n:'Vitamin E',does:'protects your cells'},{n:'Magnesium',does:'helps muscles and nerves'},{n:'Healthy fat',does:'slow, steady energy'},{n:'Fiber',does:'keeps you full'}],
    why:'A crunchy snack of healthy fat, protein, and fiber — filling and full of vitamin E.',
    pros:['Healthy fats + protein','Very filling','Vitamin E and magnesium','No cooking needed'],
    cons:['Calorie-dense (a handful is plenty)','Salted/roasted adds sodium'],
    body:'The mix of fat, protein, and fiber digests slowly, so a small handful keeps hunger away for a long time. But because fat is calorie-dense, the portion is about one closed handful.' },

  { slug:'oatmeal', name:'Oatmeal', group:'Grain', rating:'everyday', q:'oatmeal porridge',
    serving:'1 cup cooked (234 g)', calories:154,
    stats:[{k:'Carbs',v:'27 g'},{k:'Fiber',v:'4 g'},{k:'Protein',v:'6 g'},{k:'Sugar',v:'1 g (plain)'}],
    nutrients:[{n:'Fiber (beta-glucan)',does:'steadies blood sugar and cholesterol'},{n:'Manganese',does:'helps bones and metabolism'},{n:'Iron',does:'carries oxygen'},{n:'Protein',does:'keeps you full'}],
    why:'A whole grain with a special fiber that gives long, steady morning energy.',
    pros:['Long-lasting energy','Special heart-healthy fiber','Cheap and filling','Whole grain'],
    cons:['Flavored packets can be sugar bombs','Toppings can add up fast'],
    body:'Oats have a sticky fiber called beta-glucan that forms a gel in your gut, slowing digestion so you feel full and your energy stays even until lunch. Plain oats + fruit beats the sugary flavored packets.' },

  { slug:'brown_rice', name:'Brown Rice', group:'Grain', rating:'everyday', q:'brown rice',
    serving:'1 cup cooked (195 g)', calories:216,
    stats:[{k:'Carbs',v:'45 g'},{k:'Fiber',v:'4 g'},{k:'Protein',v:'5 g'},{k:'Sugar',v:'0 g'}],
    nutrients:[{n:'Fiber',does:'keeps you full and steady'},{n:'Manganese',does:'helps metabolism and bones'},{n:'Magnesium',does:'helps muscles and nerves'},{n:'B vitamins',does:'turn food into energy'}],
    why:'The whole-grain version of rice — it keeps the bran, so more fiber and steadier energy than white rice.',
    pros:['Whole grain with fiber','Steadier energy than white rice','Filling side','Cheap'],
    cons:['Still starchy — portion matters','Takes longer to cook'],
    body:'Brown rice keeps its outer bran layer, which is where the fiber and minerals live. That fiber slows the starch down, so your blood sugar rises more gently than with white rice.' },

  { slug:'whole_grain_bread', name:'Whole-Grain Bread', group:'Grain', rating:'everyday', q:'whole grain bread slices',
    serving:'1 slice (28 g)', calories:80,
    stats:[{k:'Carbs',v:'14 g'},{k:'Fiber',v:'2 g'},{k:'Protein',v:'4 g'},{k:'Sugar',v:'1 g'}],
    nutrients:[{n:'Fiber',does:'helps digestion and fullness'},{n:'B vitamins',does:'make energy'},{n:'Iron',does:'carries oxygen'},{n:'Protein',does:'keeps you full'}],
    why:'Made from the whole grain, so it has the fiber and nutrients that white bread loses.',
    pros:['More fiber than white bread','B vitamins and iron','Steadier energy','Good base for a meal'],
    cons:['"Wheat" or "multigrain" isn’t always whole grain — check the label','Can be high in sodium'],
    body:'Whole-grain flour keeps the bran and germ of the wheat, so you get fiber and minerals that white bread strips out. The fiber makes the carbs release energy more slowly.' },

  { slug:'greek_yogurt', name:'Greek Yogurt', group:'Dairy', rating:'everyday', q:'yogurt with berries',
    serving:'3/4 cup plain (170 g)', calories:100,
    stats:[{k:'Protein',v:'17 g'},{k:'Sugar',v:'6 g (natural)'},{k:'Carbs',v:'6 g'},{k:'Calcium',v:'high'}],
    nutrients:[{n:'Protein',does:'builds muscle and keeps you full'},{n:'Calcium',does:'builds strong bones'},{n:'Probiotics',does:'keep your gut healthy'},{n:'Vitamin B12',does:'makes red blood cells'}],
    why:'Strained to be extra thick, so it has double the protein of regular yogurt — plus gut-friendly probiotics.',
    pros:['Very high protein','Calcium for bones','Live probiotics for the gut','Filling snack'],
    cons:['Flavored kinds add lots of sugar','Plain can taste sour (add fruit)'],
    body:'The live "good bacteria" (probiotics) join the helpful microbes in your gut that aid digestion and your immune system. The protein and calcium build muscle and bone. Pick plain and sweeten it with fruit instead of buying the sugary flavored cups.' },

  { slug:'milk', name:'Milk', group:'Dairy', rating:'everyday', q:'glass of milk',
    serving:'1 cup (244 g)', calories:122,
    stats:[{k:'Protein',v:'8 g'},{k:'Sugar',v:'12 g (lactose)'},{k:'Fat',v:'5 g'},{k:'Calcium',v:'high'}],
    nutrients:[{n:'Calcium',does:'builds strong bones and teeth'},{n:'Vitamin D',does:'helps absorb the calcium'},{n:'Protein',does:'builds muscle'},{n:'Vitamin B12',does:'makes blood'}],
    why:'A classic bone-builder — calcium and vitamin D team up to make your bones strong.',
    pros:['Calcium + vitamin D for bones','Good protein','Hydrating','Cheap'],
    cons:['Some people can’t digest lactose','Flavored (chocolate) milk adds sugar'],
    body:'Calcium is the mineral your bones and teeth are built from, and the vitamin D added to milk is the "key" that lets your gut absorb that calcium. Your bones grow fastest while you’re young, so this matters now.' },

  { slug:'cheese', name:'Cheese', group:'Dairy', rating:'sometimes', q:'cheddar cheese',
    serving:'1 oz (28 g)', calories:115,
    stats:[{k:'Protein',v:'7 g'},{k:'Fat',v:'9 g (mostly saturated)'},{k:'Sodium',v:'180 mg'},{k:'Calcium',v:'high'}],
    nutrients:[{n:'Calcium',does:'builds bones and teeth'},{n:'Protein',does:'builds muscle'},{n:'Vitamin B12',does:'makes red blood cells'}],
    why:'Great calcium and protein, but also a lot of saturated fat and salt — tasty in smaller amounts.',
    pros:['Calcium and protein','Very filling','Adds flavor to veggies'],
    cons:['High in saturated fat','High in sodium','Easy to overeat'],
    body:'The calcium and protein are genuinely good for bones and muscle, but cheese is concentrated — the saturated fat and salt add up fast, so a slice or two beats a big pile.' },

  { slug:'pizza', name:'Pizza', group:'Meal', rating:'sometimes', q:'cheese pizza slice',
    serving:'1 slice cheese (107 g)', calories:285,
    stats:[{k:'Carbs',v:'36 g'},{k:'Fat',v:'10 g'},{k:'Protein',v:'12 g'},{k:'Sodium',v:'640 mg'}],
    nutrients:[{n:'Protein',does:'builds muscle'},{n:'Calcium',does:'from the cheese, builds bones'},{n:'Refined carbs',does:'quick energy that fades fast'}],
    why:'Not all bad — there’s protein and calcium — but the white crust, salt, and grease make it a "sometimes" food.',
    pros:['Some protein and calcium','Veggie toppings help','Filling'],
    cons:['High in sodium','White-flour crust, low fiber','Greasy, easy to overeat'],
    body:'The cheese gives protein and calcium, but the white crust is refined (little fiber) so it spikes your blood sugar, and one slice can carry a quarter of a day’s salt. Loading on veggie toppings and stopping at a slice or two makes it friendlier.' },

  { slug:'cheeseburger', name:'Cheeseburger', group:'Meal', rating:'sometimes', q:'cheeseburger',
    serving:'1 fast-food burger (~120 g)', calories:300,
    stats:[{k:'Protein',v:'15 g'},{k:'Fat',v:'14 g'},{k:'Carbs',v:'33 g'},{k:'Sodium',v:'720 mg'}],
    nutrients:[{n:'Protein',does:'builds muscle'},{n:'Iron',does:'from the beef, carries oxygen'},{n:'Saturated fat',does:'raises cholesterol if you eat a lot'}],
    why:'The beef brings real protein and iron, but the white bun, cheese, and sauces pile on fat and salt.',
    pros:['Good protein and iron','Very filling','Add lettuce/tomato for a boost'],
    cons:['High saturated fat','High sodium','Refined white bun'],
    body:'The beef patty gives protein and iron your body can use, but the saturated fat and salt are high, and the fluffy white bun adds fast carbs with little fiber. Bigger "double" burgers can top 500–800 calories on their own.' },

  { slug:'french_fries', name:'French Fries', group:'Side', rating:'treat', q:'french fries',
    serving:'medium (117 g)', calories:365,
    stats:[{k:'Carbs',v:'48 g'},{k:'Fat',v:'17 g'},{k:'Fiber',v:'4 g'},{k:'Sodium',v:'250 mg'}],
    nutrients:[{n:'Refined starch',does:'quick energy, then a crash'},{n:'Added fat',does:'lots of calories from frying'},{n:'Sodium',does:'makes your body hold water'}],
    why:'A potato is fine — but deep-frying and salting it turns it into a high-calorie treat.',
    pros:['Potato does have some potassium and fiber','Very tasty and filling'],
    cons:['Deep-fried = lots of fat and calories','High in salt','Easy to eat a huge portion'],
    body:'Frying soaks the potato in oil, tripling the calories compared with a baked potato. The salt makes you thirsty and hold onto water, and the refined starch gives a quick spike then a slump. A baked or air-fried potato gets you most of the taste with far less grease.' },

  { slug:'potato_chips', name:'Potato Chips', group:'Snack', rating:'treat', q:'potato chips',
    serving:'1 oz, ~15 chips (28 g)', calories:152,
    stats:[{k:'Carbs',v:'15 g'},{k:'Fat',v:'10 g'},{k:'Fiber',v:'1 g'},{k:'Sodium',v:'149 mg'}],
    nutrients:[{n:'Refined starch',does:'quick energy, little staying power'},{n:'Added fat',does:'lots of calories'},{n:'Sodium',does:'makes you thirsty and hold water'}],
    why:'Fried, salty, and crunchy — lots of calories with almost nothing to keep you full.',
    pros:['Convenient','Baked versions have less fat'],
    cons:['Fried and salty','Very easy to overeat a whole bag','Barely any protein or fiber'],
    body:'Because there’s almost no protein or fiber, chips don’t tell your brain you’re full, so it’s easy to eat the whole bag. The crunch and salt are engineered to make you keep reaching for more.' },

  { slug:'soda', name:'Soda', group:'Drink', rating:'treat', q:'glass of cola',
    serving:'1 can (355 ml)', calories:140,
    stats:[{k:'Sugar',v:'39 g (added)'},{k:'Carbs',v:'39 g'},{k:'Fiber',v:'0 g'},{k:'Protein',v:'0 g'}],
    nutrients:[{n:'Added sugar',does:'pure quick energy, then a crash'},{n:'Nothing else',does:'no vitamins, fiber, or protein'}],
    why:'Basically sugar-water — about 10 teaspoons of sugar in a can and zero nutrients.',
    pros:['— (there isn’t really an upside)'],
    cons:['~10 teaspoons of added sugar','No nutrients at all','Feeds cavities','Sugar crash and more hunger'],
    body:'With no fiber to slow it, the sugar floods your blood in minutes. Your body dumps out insulin to grab it, then your blood sugar can crash and leave you tired and hungrier than before. The sugar also bathes your teeth, feeding the bacteria that cause cavities.' },

  { slug:'chocolate_bar', name:'Chocolate Bar', group:'Treat', rating:'treat', q:'chocolate bar',
    serving:'1 bar (44 g)', calories:235,
    stats:[{k:'Sugar',v:'26 g (added)'},{k:'Fat',v:'13 g'},{k:'Carbs',v:'26 g'},{k:'Protein',v:'3 g'}],
    nutrients:[{n:'Added sugar',does:'quick energy, then a dip'},{n:'Fat',does:'lots of calories'},{n:'A little iron',does:'from the cocoa'}],
    why:'Sugar and fat together make it delicious and very easy to overeat — a small treat, not a snack.',
    pros:['Dark chocolate has some antioxidants','Small squares can satisfy a craving'],
    cons:['High in added sugar','High in fat and calories','Milk chocolate is mostly sugar'],
    body:'The combo of sugar and fat lights up your brain’s reward system, which is why one bite leads to another. Darker chocolate (70%+) has more cocoa and antioxidants and less sugar than milk chocolate.' },

  { slug:'ice_cream', name:'Ice Cream', group:'Treat', rating:'treat', q:'ice cream scoops',
    serving:'1/2 cup (66 g)', calories:137,
    stats:[{k:'Sugar',v:'14 g (added)'},{k:'Fat',v:'7 g'},{k:'Carbs',v:'16 g'},{k:'Calcium',v:'some'}],
    nutrients:[{n:'Added sugar',does:'quick energy, then a dip'},{n:'Saturated fat',does:'lots of calories'},{n:'A little calcium',does:'from the milk/cream'}],
    why:'Made from cream and sugar — it has a little calcium, but it’s a dessert, not a dairy serving.',
    pros:['A little calcium from the dairy','A satisfying treat in a small scoop'],
    cons:['High in added sugar','High in saturated fat','Portions are usually way over 1/2 cup'],
    body:'The tiny bit of calcium doesn’t make up for the sugar and saturated fat. Real trouble is portion size — a "bowl" is often 3–4 servings, so the sugar and calories multiply fast.' },

  { slug:'donut', name:'Donut', group:'Treat', rating:'treat', q:'glazed donut',
    serving:'1 glazed (60 g)', calories:240,
    stats:[{k:'Sugar',v:'12 g (added)'},{k:'Fat',v:'14 g'},{k:'Carbs',v:'26 g'},{k:'Fiber',v:'1 g'}],
    nutrients:[{n:'Refined flour',does:'quick energy, no staying power'},{n:'Added sugar',does:'spike then crash'},{n:'Fried fat',does:'lots of calories'}],
    why:'White flour, deep-fried, then coated in sugar — about as far from "fuel" as breakfast gets.',
    pros:['A tasty once-in-a-while treat'],
    cons:['Fried in oil','Refined flour + sugar, almost no fiber','Spikes then crashes your energy'],
    body:'It’s a triple hit: refined flour and sugar spike your blood sugar with no fiber to slow it, and frying adds a load of fat. You get fast energy that fades quickly, leaving you hungry again soon after.' }
];
